export const DOCS_PILLARS = [
  {
    id: "foundation",
    title: "1. System Foundation & Architecture",
    description: "Core platform design, live sync engine, and Nigerian currency standards.",
    icon: "architecture",
  },
  {
    id: "web-studios",
    title: "2. Client Web Content Studios",
    description: "Full CMS control over Header, Footer, Homepage, About, Contact, and SEO.",
    icon: "web",
  },
  {
    id: "creative-events",
    title: "3. Creative, Events & Media",
    description: "Talents roster, showcase scheduling, ticket quotas, blog, and media library.",
    icon: "events",
  },
  {
    id: "operations-finance",
    title: "4. Operations, Finance & Inquiries",
    description: "Giving causes, Paystack reconciliation, visitor inquiries, and booking leads.",
    icon: "finance",
  },
  {
    id: "governance-sops",
    title: "5. Security, Administration & SOPs",
    description: "Role-based access, security audit trails, and staff standard operating procedures.",
    icon: "security",
  },
];

export const DOCS_CHAPTERS = [
  // PILLAR 1: FOUNDATION
  {
    slug: "architecture",
    pillarId: "foundation",
    title: "Platform Overview & Live Web Sync",
    badge: "Architecture",
    readTime: "4 min read",
    targetAudience: ["All Administrators", "Executives", "Operations"],
    summary:
      "Understand the relationship between the private Royz House Admin Studio and the public-facing client website, including how changes take effect instantly without code deployments.",
    directAdminUrl: "/",
    clientWebPath: "/",
    webImpact: "Every content mutation published here pushes live instantly to the public website.",
    quickReference: [
      { label: "Admin Address", value: "admin.royzhouz.com" },
      { label: "Public Website", value: "royzhouz.com" },
      { label: "Deployment Needed?", value: "No (100% Instant Live Sync)" },
      { label: "Security", value: "Role-Based Access + Audit Logging" },
    ],
    sections: [
      {
        heading: "The Decoupled Architecture",
        content:
          "Royz House operates on a headless architecture. The Admin Studio (/admin) is a private, authenticated control center where business operators manage site copy, events, tickets, and creative rosters. The Public Client (/web) is the consumer-facing frontend. Both connect to a unified database.",
        steps: [
          "1. Log into the Admin Studio using your authorized staff credentials.",
          "2. Navigate to the desired module via the left sidebar (e.g., Homepage, Events, Contact).",
          "3. Make your content adjustments, upload imagery, or update pricing.",
          "4. Click 'Save Changes' or 'Publish'. The database updates and the public website renders the latest content immediately.",
        ],
        alert: {
          type: "tip",
          text: "You never need to contact software developers to update copy, change ticket prices, or post emergency announcements.",
        },
      },
      {
        heading: "Enterprise Security & Privacy",
        content:
          "Payment processing is securely handled via Paystack. Customer credit card numbers, CVVs, and banking secrets are never processed or stored on our servers. Administrative sessions are guarded by JWT-encrypted cookies and multi-role permission checks.",
        checklist: [
          "Staff members must never share login credentials.",
          "Every edit, publication, or deletion is stamped with an immutable audit log entry.",
          "Sessions automatically expire upon prolonged inactivity.",
        ],
      },
    ],
  },
  {
    slug: "currency-standards",
    pillarId: "foundation",
    title: "Nigerian Naira (₦) Currency Standard",
    badge: "Financial Standard",
    readTime: "3 min read",
    targetAudience: ["Finance Staff", "Event Coordinators", "Donations Managers"],
    summary:
      "All financial representations across Royz House are standardized in Nigerian Naira (₦ / NGN), with automated conversion for Paystack gateway settlement.",
    directAdminUrl: "/donations",
    clientWebPath: "/donate",
    webImpact: "All public ticket prices, donation cause goals, and preset chips display the Naira symbol (₦).",
    quickReference: [
      { label: "Default Currency", value: "Nigerian Naira (₦ / NGN)" },
      { label: "Number Formatting", value: "en-NG standard (e.g. ₦25,000)" },
      { label: "Paystack Settlement", value: "Auto-multiplied to Kobo (x100)" },
      { label: "Alternative Currencies", value: "USD, EUR, GBP supported for international bookings" },
    ],
    sections: [
      {
        heading: "Why Nigerian Naira is Default",
        content:
          "Royz House primarily services Nigerian creative arts and cultural communities. To eliminate pricing confusion and exchange volatility, all ticket admissions, giving campaigns, and financial summaries are anchored in Naira (₦).",
        steps: [
          "1. When entering an event ticket price, input the exact integer amount in Naira (e.g., 5000 for ₦5,000).",
          "2. When creating a donation cause, enter the target goal in Naira (e.g., 5000000 for ₦5,000,000).",
          "3. Paystack handles charges in Kobo behind the scenes (₦1 = 100 kobo). The admin displays reconciled Naira figures.",
        ],
        fieldsTable: [
          {
            name: "Ticket Price (₦)",
            type: "Number Input",
            required: true,
            description: "Price per admission pass in Nigerian Naira.",
            format: "Positive integer without commas (e.g. 5000 for ₦5,000). Enter 0 for Free admission.",
            webImpact: "Displays as '₦5,000' or 'Free' on the event ticket selector.",
          },
          {
            name: "Donation Target Goal (₦)",
            type: "Number Input",
            required: true,
            description: "Fundraising target for a specific philanthropic cause.",
            format: "Integer in Naira (e.g. 5000000 for ₦5,000,000). Minimum ₦10,000.",
            webImpact: "Calculates live completion percentage for the cause progress bar.",
          },
          {
            name: "Talent Booking Rate",
            type: "Currency + Amount",
            required: false,
            description: "Baseline artist engagement fee for private bookings.",
            format: "Currency dropdown (₦, $, €, £) + numeric fee (e.g. ₦250,000).",
            webImpact: "Displayed on the talent's profile card as 'From ₦250,000'.",
          },
        ],
        alert: {
          type: "important",
          text: "Never add manual currency symbols into numerical input fields. The system automatically attaches the ₦ adornment.",
        },
      },
    ],
  },
  {
    slug: "dashboard-overview",
    pillarId: "foundation",
    title: "Workspace & Executive Dashboard",
    badge: "Analytics & Monitoring",
    readTime: "4 min read",
    targetAudience: ["Executives", "Operations Managers", "Team Leads"],
    summary:
      "The executive dashboard provides a single-pane-of-glass overview of company operations, financial totals, creative roster size, and recent administrative actions.",
    directAdminUrl: "/",
    clientWebPath: "/",
    webImpact: "Internal monitoring tool. Displays real-time counts pulled directly from production data.",
    quickReference: [
      { label: "Metrics Frequency", value: "Real-time query on page load" },
      { label: "Audit Feed", value: "Latest 10 admin operations" },
      { label: "Quick Launch", value: "Direct links to upcoming events and spotlight talents" },
    ],
    sections: [
      {
        heading: "Key Performance Indicator (KPI) Cards",
        content:
          "Four executive cards summarize key operational health metrics at a glance: Total Published Events, Cumulative Ticket Revenue in Naira (₦), Active Talents, and Total Donations Verified in Naira (₦).",
        steps: [
          "1. Total Published Events: Counts all active showcases visible to website visitors.",
          "2. Ticket Revenue: Real-time sum of all successful Paystack ticket sales.",
          "3. Active Talents: Total approved creatives appearing on the public talents roster.",
          "4. Total Giving Raised: Reconciled sum of all verified donation transactions.",
        ],
        fieldsTable: [
          {
            name: "Published Events Metric",
            type: "Auto Metric Counter",
            required: false,
            description: "Real-time query counting events with status='published'.",
            format: "Integer count. Refreshes on page view.",
            webImpact: "Reflects the total live showcases available on /events.",
          },
          {
            name: "Cumulative Ticket Revenue (₦)",
            type: "Auto Financial Sum",
            required: false,
            description: "Aggregate sum of confirmed ticket orders settled through Paystack.",
            format: "Formatted in Nigerian Naira (e.g. ₦1,450,000).",
            webImpact: "Internal executive revenue indicator.",
          },
          {
            name: "Active Talents Count",
            type: "Auto Metric Counter",
            required: false,
            description: "Count of all talents marked as published in the roster.",
            format: "Integer count.",
            webImpact: "Reflects the total talent profiles visible on /talents.",
          },
          {
            name: "Total Giving Raised (₦)",
            type: "Auto Financial Sum",
            required: false,
            description: "Sum of verified donor contributions across all causes.",
            format: "Formatted in Nigerian Naira (e.g. ₦8,200,000).",
            webImpact: "Internal fundraising progress tracker.",
          },
        ],
      },
    ],
  },

  // PILLAR 2: CLIENT WEB STUDIOS
  {
    slug: "global-settings",
    pillarId: "web-studios",
    title: "Website Global Header, Footer & Socials",
    badge: "Sitewide CMS",
    readTime: "5 min read",
    targetAudience: ["Marketing", "Editorial", "Web Managers"],
    summary:
      "Control the global layout elements that appear across every single page of the public website: navigation bars, footer links, social handles, and company address.",
    directAdminUrl: "/website",
    clientWebPath: "/",
    webImpact: "Updates the navigation bar, footer columns, and social icons on all public pages simultaneously.",
    quickReference: [
      { label: "Primary Menu Items", value: "Labels, paths, and ordering" },
      { label: "Footer Columns", value: "Categorized links (Explore, Legal, etc.)" },
      { label: "Social Networks", value: "Instagram, YouTube, TikTok, X, LinkedIn" },
      { label: "Headquarters", value: "Email, telephone, and physical location" },
    ],
    sections: [
      {
        heading: "Managing Navigation Bar & Sitewide Fields",
        content:
          "The header menu allows visitors to easily browse key sections of Royz House. Administrators can add new links, change existing labels, or reorder menu items without writing code.",
        steps: [
          "1. Go to 'Website' in the Admin navigation.",
          "2. Select the 'Header Navigation' tab.",
          "3. To modify a link, click inside its Label or URL field.",
          "4. To hide a menu item without deleting it, switch status from 'Published' to 'Draft'.",
          "5. Click 'Save Global Navigation' at the bottom to publish changes to the live site.",
        ],
        fieldsTable: [
          {
            name: "Navigation Label",
            type: "Text Input",
            required: true,
            description: "The text that appears in the top website menu.",
            format: "Short title, 1-2 words (e.g. 'Events', 'Talents', 'About Us'). Max 20 chars.",
            webImpact: "Appears in desktop header and mobile slide-out menu.",
          },
          {
            name: "Navigation Path / URL",
            type: "URL / Path Input",
            required: true,
            description: "Destination URL or relative page path.",
            format: "Relative path (e.g. '/events', '/donate') or external HTTPS URL.",
            webImpact: "Directs users when clicking the navigation link.",
          },
          {
            name: "Menu Status",
            type: "Select Dropdown",
            required: true,
            description: "Controls whether the link is visible on the live site.",
            format: "Options: 'Published' (Visible) or 'Draft' (Hidden).",
            webImpact: "Instantly shows or hides the link sitewide.",
          },
          {
            name: "Instagram Channel URL",
            type: "URL Input",
            required: false,
            description: "Link to official Royz House Instagram account.",
            format: "Full URL (e.g. https://instagram.com/royzhouz).",
            webImpact: "Powers the Instagram icon in header and footer.",
          },
          {
            name: "YouTube Channel URL",
            type: "URL Input",
            required: false,
            description: "Link to official Royz House YouTube channel.",
            format: "Full URL (e.g. https://youtube.com/@royzhouz).",
            webImpact: "Powers YouTube icon in header and footer.",
          },
          {
            name: "TikTok Profile URL",
            type: "URL Input",
            required: false,
            description: "Link to official TikTok page.",
            format: "Full URL (e.g. https://tiktok.com/@royzhouz).",
            webImpact: "Powers TikTok icon in header and footer.",
          },
          {
            name: "X (Twitter) Profile URL",
            type: "URL Input",
            required: false,
            description: "Link to official X profile.",
            format: "Full URL (e.g. https://x.com/royzhouz).",
            webImpact: "Powers X icon in header and footer.",
          },
          {
            name: "Official Inquiries Email",
            type: "Email Input",
            required: true,
            description: "Primary contact email displayed across the site.",
            format: "Valid email (e.g. contact@royzhouz.com).",
            webImpact: "Rendered in footer, contact cards, and mailto links.",
          },
          {
            name: "Official Phone Line",
            type: "Phone Input",
            required: true,
            description: "Primary telephone helpline for client inquiries.",
            format: "International format (e.g. +234 816 023 2043).",
            webImpact: "Rendered in website footer and click-to-call links.",
          },
          {
            name: "Physical Studio Address",
            type: "Textarea",
            required: true,
            description: "Physical address of Royz House headquarters.",
            format: "Full street address, city, and state.",
            webImpact: "Rendered in website footer and location sections.",
          },
        ],
      },
    ],
  },
  {
    slug: "homepage-studio",
    pillarId: "web-studios",
    title: "Homepage & Sections Studio",
    badge: "Landing Page",
    readTime: "6 min read",
    targetAudience: ["Marketing", "Content Editors", "Creative Directors"],
    summary:
      "Manage all hero headlines, banner imagery, talent spotlights, upcoming showcase marquees, and dynamic call-to-actions on the public front door of Royz House.",
    directAdminUrl: "/homepage",
    clientWebPath: "/",
    webImpact: "Instantly customizes the landing page seen by all first-time visitors.",
    quickReference: [
      { label: "Hero Headline", value: "Primary bold mission statement" },
      { label: "Call to Actions", value: "Primary (e.g. Explore) & Secondary (e.g. Donate)" },
      { label: "Spotlight Section", value: "Featured creatives marquee" },
      { label: "Hero Artwork", value: "High-resolution 1920x1080 banner image" },
    ],
    sections: [
      {
        heading: "Hero Banner & Sections Form Controls",
        content:
          "The hero banner is the first visual element visitors see. It establishes brand identity and guides visitors toward primary conversion goals (booking talents, attending events, donating).",
        steps: [
          "1. Navigate to 'Homepage' in the left menu.",
          "2. In the 'Hero Section' card, update the Main Headline and Subtitle.",
          "3. Set the Primary Button Text (e.g., 'Discover Talents') and Target URL (e.g., '/talents').",
          "4. Set the Secondary Button Text (e.g., 'Support Our Cause') and Target URL (e.g., '/donate').",
          "5. Upload or replace the Hero Background Image.",
          "6. Click 'Save Homepage Content' to commit changes.",
        ],
        fieldsTable: [
          {
            name: "Hero Eyebrow Tag",
            type: "Text Input",
            required: false,
            description: "Small uppercase category tag above the main headline.",
            format: "1-4 words (e.g. 'CREATIVE COLLECTIVE & AGENCY'). Max 40 chars.",
            webImpact: "Displays in amber text above the hero headline.",
          },
          {
            name: "Hero Main Headline",
            type: "Text Input",
            required: true,
            description: "The primary bold statement on the landing page.",
            format: "Punchy, inspiring copy (e.g. 'HOME OF VISIONARIES & CREATIVES'). Max 80 chars.",
            webImpact: "Rendered as the primary H1 headline on royzhouz.com.",
          },
          {
            name: "Hero Subtitle / Mission Copy",
            type: "Textarea",
            required: true,
            description: "Two to three sentences explaining Royz House's mission.",
            format: "Compelling narrative. Max 250 characters.",
            webImpact: "Displayed beneath the main headline in muted gray font.",
          },
          {
            name: "Primary CTA Label",
            type: "Text Input",
            required: true,
            description: "Label for the primary colored action button.",
            format: "Action verb (e.g. 'Explore Talents', 'Book a Show'). Max 25 chars.",
            webImpact: "Primary button on the homepage hero.",
          },
          {
            name: "Primary CTA Link",
            type: "Path / URL Input",
            required: true,
            description: "Destination URL for the primary button.",
            format: "Relative path (e.g. '/talents') or external URL.",
            webImpact: "Navigates visitor when clicking primary button.",
          },
          {
            name: "Secondary CTA Label",
            type: "Text Input",
            required: false,
            description: "Label for the outlined secondary action button.",
            format: "Action verb (e.g. 'Support Our Cause'). Max 25 chars.",
            webImpact: "Secondary button next to the primary button.",
          },
          {
            name: "Secondary CTA Link",
            type: "Path / URL Input",
            required: false,
            description: "Destination URL for the secondary button.",
            format: "Relative path (e.g. '/donate').",
            webImpact: "Navigates visitor when clicking secondary button.",
          },
          {
            name: "Hero Background Artwork",
            type: "Media Picker / Upload",
            required: true,
            description: "High-resolution background banner image.",
            format: "1920x1080px (16:9 ratio), WebP or JPEG under 1.5MB.",
            webImpact: "Renders as the backdrop behind the hero text overlay.",
          },
          {
            name: "Talents Marquee Limit",
            type: "Number Input",
            required: false,
            description: "Maximum number of talent cards displayed on the homepage slider.",
            format: "Integer between 4 and 12.",
            webImpact: "Limits the number of profiles shown in the homepage carousel.",
          },
          {
            name: "Upcoming Events Limit",
            type: "Number Input",
            required: false,
            description: "Number of upcoming events displayed on the homepage.",
            format: "Integer between 2 and 6.",
            webImpact: "Controls how many event cards render before 'View All'.",
          },
        ],
      },
    ],
  },
  {
    slug: "about-studio",
    pillarId: "web-studios",
    title: "About Us Page Studio",
    badge: "Brand Story",
    readTime: "5 min read",
    targetAudience: ["Marketing", "Editorial", "Public Relations"],
    summary:
      "Tell the Royz House story. Manage mission statements, core pillars, historical milestones, executive leadership profiles, and studio photo moments.",
    directAdminUrl: "/about",
    clientWebPath: "/about",
    webImpact: "Updates the public brand story, leadership team, and cultural legacy page.",
    quickReference: [
      { label: "Mission & Vision", value: "Core organization philosophy" },
      { label: "Leadership Profiles", value: "Photos, names, roles, and bios" },
      { label: "Timeline Milestones", value: "Key historical dates & achievements" },
    ],
    sections: [
      {
        heading: "Leadership Team & Brand Narrative Fields",
        content:
          "Showcase executive directors, resident choreographers, sound engineers, and creative leads with headshots and professional bios.",
        steps: [
          "1. Open 'About' in the Admin sidebar.",
          "2. Click the 'Leadership & Team' tab.",
          "3. Click 'Add Team Member' or edit an existing card.",
          "4. Provide the member's Full Name, Title/Role, Short Bio, and high-resolution portrait.",
          "5. Click 'Save About Page' to push updates to the public web.",
        ],
        fieldsTable: [
          {
            name: "Mission Statement",
            type: "Textarea",
            required: true,
            description: "Core mission copy articulating Royz House's creative purpose.",
            format: "1-2 paragraphs. Max 500 characters.",
            webImpact: "Displays at the top of /about in the mission callout card.",
          },
          {
            name: "Team Member Full Name",
            type: "Text Input",
            required: true,
            description: "Full name of the executive or creative leader.",
            format: "Title Case (e.g. 'Victor O. Royz'). Max 60 chars.",
            webImpact: "Rendered below the team portrait card.",
          },
          {
            name: "Team Member Role / Title",
            type: "Text Input",
            required: true,
            description: "Official organizational title.",
            format: "e.g. 'Founder & Creative Director', 'Lead Choreographer'. Max 50 chars.",
            webImpact: "Rendered in amber subtitle font below the team member's name.",
          },
          {
            name: "Team Member Bio",
            type: "Textarea",
            required: false,
            description: "Short professional biography highlighting achievements.",
            format: "1 paragraph (80-140 words).",
            webImpact: "Appears in hover modal or expanded team drawer.",
          },
          {
            name: "Team Portrait Image",
            type: "Media Picker / Upload",
            required: true,
            description: "High-resolution professional headshot.",
            format: "Square 1:1 or portrait 4:5 ratio, min 600x600px WebP/JPEG.",
            webImpact: "Renders in the team leadership photo grid.",
          },
          {
            name: "Milestone Year",
            type: "Text / Number Input",
            required: true,
            description: "Calendar year of the historical company milestone.",
            format: "4-digit year (e.g. '2024', '2026').",
            webImpact: "Timeline node marker on the heritage timeline.",
          },
          {
            name: "Milestone Description",
            type: "Textarea",
            required: true,
            description: "Key achievement or breakthrough accomplished in that year.",
            format: "Concise summary (max 180 chars).",
            webImpact: "Rendered beside the timeline year marker.",
          },
        ],
      },
    ],
  },
  {
    slug: "contact-page-studio",
    pillarId: "web-studios",
    title: "Contact Page Studio (Live CMS)",
    badge: "Contact CMS",
    readTime: "5 min read",
    targetAudience: ["Operations", "Customer Care", "Facility Managers"],
    summary:
      "Full CMS controls over the public Contact page: hero banner text, department emails, physical studio coordinates, talent casting CTA cards, and interactive FAQs.",
    directAdminUrl: "/contacts",
    clientWebPath: "/contact",
    webImpact: "Dynamically populates all text, contact boxes, studio location map, and FAQs on /contact.",
    quickReference: [
      { label: "Admin Route", value: "/contacts -> Contact Page Studio Tab" },
      { label: "Controlled Tabs", value: "Hero, Inquiries, Map/Studio, FAQs, Talent CTA, SEO" },
      { label: "Real-time Fallback", value: "Zero downtime with resilient defaults" },
    ],
    sections: [
      {
        heading: "Contact Page Studio Form Fields & Tabs",
        content:
          "The Contact page features direct contact cards for General Inquiries, Talent Bookings, and Media/Press, alongside Royz House studio address and interactive Google Map coordinates.",
        steps: [
          "1. Navigate to 'Contacts' in Admin, then switch to the 'Contact Page Studio' tab.",
          "2. Under 'Department Inquiries', edit specific email addresses and operating hours for each department.",
          "3. Under 'Studio Location & Map', enter the physical address, city, phone line, and embed map coordinates.",
          "4. Under 'Frequently Asked Questions', add or edit accordion items for common visitor questions.",
          "5. Click 'Save Contact Page Settings'. Open royzhouz.com/contact to verify immediately.",
        ],
        fieldsTable: [
          {
            name: "Hero Eyebrow",
            type: "Text Input",
            required: false,
            description: "Small category badge above the Contact title.",
            format: "1-3 words (e.g. 'GET IN TOUCH'). Max 30 chars.",
            webImpact: "Appears above the main headline on /contact.",
          },
          {
            name: "Contact Hero Title",
            type: "Text Input",
            required: true,
            description: "Main headline greeting visitors on /contact.",
            format: "e.g. 'Connect with Royz House'. Max 60 chars.",
            webImpact: "Primary H1 headline on the contact page.",
          },
          {
            name: "Contact Hero Subtitle",
            type: "Textarea",
            required: true,
            description: "Introductory copy explaining how staff responds to inquiries.",
            format: "1-2 sentences (max 200 chars).",
            webImpact: "Displayed beneath the main contact title.",
          },
          {
            name: "Department Name",
            type: "Text Input",
            required: true,
            description: "Name of the specialized contact box.",
            format: "e.g. 'General Inquiries', 'Talent Bookings', 'Press & Media'.",
            webImpact: "Card header on the inquiries grid.",
          },
          {
            name: "Department Email",
            type: "Email Input",
            required: true,
            description: "Dedicated inbox for that specific department.",
            format: "Valid email (e.g. bookings@royzhouz.com).",
            webImpact: "Rendered as clickable mailto link on the card.",
          },
          {
            name: "Operating Hours",
            type: "Text Input",
            required: true,
            description: "Working hours for staff responses.",
            format: "e.g. 'Mon - Fri: 9:00 AM - 6:00 PM WAT'.",
            webImpact: "Displays operating schedule inside the department card.",
          },
          {
            name: "Average Response Time",
            type: "Text Input",
            required: true,
            description: "Expected turnaround time for inquiries.",
            format: "e.g. 'Within 24 business hours'.",
            webImpact: "Sets visitor expectations directly on the contact card.",
          },
          {
            name: "Studio Street Address",
            type: "Text Input",
            required: true,
            description: "Physical street address of Royz House creative studio.",
            format: "e.g. '12 Admiralty Way, Lekki Phase 1'.",
            webImpact: "Rendered in the Studio Location card on /contact.",
          },
          {
            name: "Studio City & State",
            type: "Text Input",
            required: true,
            description: "City and geographic state.",
            format: "e.g. 'Lagos, Nigeria'.",
            webImpact: "Rendered below the street address.",
          },
          {
            name: "Google Map Embed URL",
            type: "URL Input",
            required: true,
            description: "Embed link from Google Maps iframe.",
            format: "HTTPS iframe src URL from Google Maps embed share dialog.",
            webImpact: "Renders the interactive map preview on /contact.",
          },
          {
            name: "FAQ Question",
            type: "Text Input",
            required: true,
            description: "Frequently asked visitor question.",
            format: "Question phrasing (e.g. 'How do I audition for Royz House?').",
            webImpact: "Accordion header in the FAQ section.",
          },
          {
            name: "FAQ Answer",
            type: "Textarea",
            required: true,
            description: "Clear, helpful answer explaining the procedure.",
            format: "1-2 paragraphs of guidance.",
            webImpact: "Expands when visitor clicks the question accordion.",
          },
          {
            name: "Talent CTA Heading",
            type: "Text Input",
            required: true,
            description: "Heading for the bottom recruitment banner.",
            format: "e.g. 'Are You a Visionary Talent? Join Our Roster'.",
            webImpact: "Banner title at the bottom of /contact.",
          },
          {
            name: "Talent CTA Button Link",
            type: "Path / URL Input",
            required: true,
            description: "Destination URL for talent auditions.",
            format: "e.g. '/join' or '/talents'.",
            webImpact: "Directs applicant to audition submission form.",
          },
        ],
      },
    ],
  },
  {
    slug: "seo-social-cards",
    pillarId: "web-studios",
    title: "Search Engine Optimization (SEO) & Social Cards",
    badge: "Discovery & Social",
    readTime: "4 min read",
    targetAudience: ["Marketing", "Growth", "Editorial"],
    summary:
      "Control how Royz House pages rank on Google and how links appear when shared on WhatsApp, iMessage, Twitter/X, and Facebook.",
    directAdminUrl: "/seo",
    clientWebPath: "/",
    webImpact: "Generates HTML meta tags, OpenGraph preview cards, and search engine snippets.",
    quickReference: [
      { label: "Meta Title", value: "Recommended 50-60 characters" },
      { label: "Meta Description", value: "Recommended 140-160 characters" },
      { label: "OG Image", value: "1200x630px social banner" },
    ],
    sections: [
      {
        heading: "SEO Studio Schema & Fields Reference",
        content:
          "When users share a link to Royz House on WhatsApp or social media, a preview card with a title, snippet, and image appears. You can customize this per page.",
        steps: [
          "1. Go to 'SEO' in the Admin sidebar.",
          "2. Select the page you wish to optimize (Homepage, Events, Talents, Donate).",
          "3. Enter an engaging Social Title and 2-sentence Social Description.",
          "4. Upload an OpenGraph Image (1200x630 pixels) featuring Royz House branding.",
          "5. Click 'Save SEO Settings'.",
        ],
        fieldsTable: [
          {
            name: "Target Page Selector",
            type: "Select Dropdown",
            required: true,
            description: "Choose which public website page to optimize.",
            format: "Options: 'Homepage (/)' , 'Events (/events)', 'Talents (/talents)', 'Donate (/donate)', 'About (/about)', 'Contact (/contact)'.",
            webImpact: "Applies SEO tags to the selected route.",
          },
          {
            name: "Meta Title (HTML <title>)",
            type: "Text Input",
            required: true,
            description: "The title shown on Google search results and browser tabs.",
            format: "50-60 characters. Include brand name (e.g. 'Upcoming Showcases & Live Events | Royz House').",
            webImpact: "Primary search engine snippet headline.",
          },
          {
            name: "Meta Description",
            type: "Textarea",
            required: true,
            description: "Summary blurb displayed under the title in Google search results.",
            format: "140-160 characters. Compelling summary with call to action.",
            webImpact: "Search snippet description on Google/Bing.",
          },
          {
            name: "OpenGraph Social Title (og:title)",
            type: "Text Input",
            required: true,
            description: "Bold headline used when link is shared on WhatsApp, iMessage, X, Facebook.",
            format: "Catchy headline (max 70 chars).",
            webImpact: "Social preview card headline.",
          },
          {
            name: "OpenGraph Description (og:description)",
            type: "Textarea",
            required: true,
            description: "Subtitle copy appearing on social sharing cards.",
            format: "1-2 sentences (max 150 chars).",
            webImpact: "Social preview card body text.",
          },
          {
            name: "OpenGraph Banner Image (og:image)",
            type: "Media Picker / Upload",
            required: true,
            description: "Promotional card image generated during social sharing.",
            format: "1200x630 pixels (1.91:1 ratio), JPEG or PNG under 1MB.",
            webImpact: "The large picture banner attached to WhatsApp/Twitter link shares.",
          },
          {
            name: "Twitter Card Format",
            type: "Select Dropdown",
            required: false,
            description: "Layout format for links shared on Twitter / X.",
            format: "Options: 'summary_large_image' (Recommended) or 'summary'.",
            webImpact: "Determines whether card appears large or compact on X.",
          },
        ],
      },
    ],
  },

  // PILLAR 3: CREATIVE, EVENTS & MEDIA
  {
    slug: "talents-roster",
    pillarId: "creative-events",
    title: "Talents Roster & Creative Showcase",
    badge: "Creative Hub",
    readTime: "6 min read",
    targetAudience: ["Talent Managers", "A&R", "Creative Directors"],
    summary:
      "Curate the creative roster. Publish new artists, dancers, choreographers, and producers. Configure performance genres, showcase media, and booking rates.",
    directAdminUrl: "/talents",
    clientWebPath: "/talents",
    webImpact: "Controls talent cards, detailed artist profiles, and the talent filter grid on the public web.",
    quickReference: [
      { label: "Categories", value: "Dance, Music, Vocalist, Producer, Choreography" },
      { label: "Booking Rates", value: "Standardized in Naira (₦) or foreign currency" },
      { label: "Profile Status", value: "Draft (Hidden) or Published (Live)" },
      { label: "Spotlight Tag", value: "Highlights artist on the Homepage" },
    ],
    sections: [
      {
        heading: "Talent Profile Form Fields Reference",
        content:
          "Adding a talent makes them discoverable on the public website and enables event producers to submit private booking requests.",
        steps: [
          "1. Navigate to 'Talents' in the sidebar.",
          "2. Click the 'Add Talent' button in the top right corner.",
          "3. Enter the Stage Name, Real Name, and primary Creative Discipline.",
          "4. Write an artist bio highlighting their achievements and signature style.",
          "5. Upload a high-resolution portrait headshot.",
          "6. Set base booking rates (defaults to ₦).",
          "7. Toggle 'Spotlight on Homepage' if desired.",
          "8. Set status to 'Published' and click 'Save Profile'.",
        ],
        fieldsTable: [
          {
            name: "Stage Name / Display Name",
            type: "Text Input",
            required: true,
            description: "Public artist or performer moniker.",
            format: "e.g. 'Aura Vibe', 'DJ Chrono'. Max 50 chars.",
            webImpact: "Primary heading on artist cards and detail page.",
          },
          {
            name: "Real Full Name",
            type: "Text Input",
            required: false,
            description: "Legal name for contracting and booking records.",
            format: "Legal Name. Stored internally.",
            webImpact: "Internal administrative reference.",
          },
          {
            name: "URL Slug",
            type: "Text Input",
            required: true,
            description: "Unique URL identifier for the talent's page.",
            format: "Lowercase, hyphens only (e.g. 'aura-vibe'). Auto-generated from stage name.",
            webImpact: "Forms the public web address: royzhouz.com/talents/aura-vibe.",
          },
          {
            name: "Creative Discipline / Category",
            type: "Select Dropdown",
            required: true,
            description: "Primary artistic genre or craft.",
            format: "Options: 'Afrobeats Dance', 'Contemporary Dance', 'Hip-Hop Vocalist', 'Music Producer', 'Choreographer'.",
            webImpact: "Filter tag on the talent discovery grid.",
          },
          {
            name: "Artist Headline",
            type: "Text Input",
            required: true,
            description: "One-sentence catchphrase summarizing the talent's style.",
            format: "e.g. 'Pioneer of Afro-Futuristic Street Dance'. Max 80 chars.",
            webImpact: "Subheadline beneath the artist's name.",
          },
          {
            name: "Artist Bio",
            type: "Rich Textarea",
            required: true,
            description: "Complete artistic background, achievements, and career history.",
            format: "2-4 paragraphs with formatting.",
            webImpact: "Main 'About' story on the talent's profile page.",
          },
          {
            name: "Profile Portrait Image",
            type: "Media Picker / Upload",
            required: true,
            description: "High-resolution signature headshot.",
            format: "Portrait 4:5 or 3:4 ratio, min 800x1000px WebP/JPEG.",
            webImpact: "Main image on talent cards and profile banner.",
          },
          {
            name: "Booking Currency",
            type: "Select Dropdown",
            required: true,
            description: "Currency for quoting artist booking fees.",
            format: "Default: 'NGN (₦)'. Also supports 'USD ($)', 'EUR (€)', 'GBP (£)'.",
            webImpact: "Currency symbol shown alongside the rate.",
          },
          {
            name: "Base Booking Fee Amount",
            type: "Number Input",
            required: false,
            description: "Starting price for hiring this talent for private engagements.",
            format: "Numeric integer (e.g. 250000 for ₦250,000).",
            webImpact: "Displayed as 'From ₦250,000' on the profile card.",
          },
          {
            name: "Spotlight on Homepage",
            type: "Toggle Switch",
            required: false,
            description: "Pins the artist to the top-tier carousel on the homepage.",
            format: "Boolean (Active / Inactive).",
            webImpact: "Features the artist in the homepage talent marquee.",
          },
          {
            name: "Publication Status",
            type: "Select Dropdown",
            required: true,
            description: "Controls public profile visibility.",
            format: "Options: 'Published' (Live on web) or 'Draft' (Hidden in admin).",
            webImpact: "Instantly publishes or unpublishes the profile.",
          },
          {
            name: "Social Handles (Instagram, YouTube, Spotify)",
            type: "URL Inputs",
            required: false,
            description: "Links to artist's music streaming and social presence.",
            format: "Full profile URLs.",
            webImpact: "Interactive social badges on the artist profile.",
          },
        ],
      },
    ],
  },
  {
    slug: "events-tickets",
    pillarId: "creative-events",
    title: "Events, Showcases & Ticket Inventories",
    badge: "Ticketing & Live Shows",
    readTime: "7 min read",
    targetAudience: ["Event Coordinators", "Ticketing Managers", "Operations"],
    summary:
      "Create live showcases, concerts, dance battles, and workshops. Manage venue details, dates, ticket categories (VIP, Regular, Table) in Naira (₦), and inventory caps.",
    directAdminUrl: "/events",
    clientWebPath: "/events",
    webImpact: "Powers the public events calendar, countdown timers, ticket selection, and Paystack checkout.",
    quickReference: [
      { label: "Currency", value: "Nigerian Naira (₦)" },
      { label: "Ticket Types", value: "Regular, VIP, Table / Backstage Pass" },
      { label: "Inventory Tracking", value: "Real-time sold vs. capacity quota" },
      { label: "Event Status", value: "Draft, Upcoming, Sold Out, Completed" },
    ],
    sections: [
      {
        heading: "Event Showcase & Ticket Tier Form Fields",
        content:
          "Events can be free admission or paid ticketed productions. Setting capacity limits guarantees you never oversell your venue.",
        steps: [
          "1. Go to 'Events' in the Admin sidebar.",
          "2. Click 'Create Event'.",
          "3. Fill in the Showcase Title, Short Description, and Comprehensive Details.",
          "4. Select Event Category (Concert, Dance Showcase, Workshop, Networking).",
          "5. Set the Start Date, Start Time, and Venue Location (or Online Link).",
          "6. Upload a 16:9 promotional flyer or stage poster.",
          "7. Under 'Ticket Configuration', click 'Add Ticket Tier':",
          "   - Name: e.g., 'Regular Admission', 'VIP Lounge', 'VIP Table of 5'",
          "   - Price (₦): Enter numeric amount (e.g. 10000 for ₦10,000, or 0 for Free)",
          "   - Quota: Maximum tickets available for this tier (e.g., 200)",
          "8. Set status to 'Published' and save. Visitors can now purchase tickets immediately.",
        ],
        fieldsTable: [
          {
            name: "Showcase Title",
            type: "Text Input",
            required: true,
            description: "Official name of the event or production.",
            format: "e.g. 'Royz Street Dance Championship 2026'. Max 100 chars.",
            webImpact: "Event title across listings, countdowns, and ticket checkout.",
          },
          {
            name: "Event Category",
            type: "Select Dropdown",
            required: true,
            description: "Showcase classification.",
            format: "Options: 'Live Concert', 'Dance Showcase', 'Workshop / Masterclass', 'Networking'.",
            webImpact: "Filter tab on the events discovery page.",
          },
          {
            name: "Start Date & Time",
            type: "Date-Time Picker",
            required: true,
            description: "Opening curtain date and time.",
            format: "YYYY-MM-DD HH:MM (WAT).",
            webImpact: "Powers the live countdown timer and calendar card.",
          },
          {
            name: "End Date & Time",
            type: "Date-Time Picker",
            required: false,
            description: "Expected event wrap date and time.",
            format: "YYYY-MM-DD HH:MM (WAT).",
            webImpact: "Displayed on the event details sidebar.",
          },
          {
            name: "Venue Name",
            type: "Text Input",
            required: true,
            description: "Facility or hall hosting the showcase.",
            format: "e.g. 'Eko Convention Centre' or 'Royz House Main Stage'.",
            webImpact: "Displayed prominently beside the event pin icon.",
          },
          {
            name: "Physical Venue Address",
            type: "Text Input",
            required: true,
            description: "Exact street address for attendee GPS navigation.",
            format: "Full street address, district, and city.",
            webImpact: "Directions link on the public event page.",
          },
          {
            name: "Event Flyer / Cover Artwork",
            type: "Media Picker / Upload",
            required: true,
            description: "High-resolution promotional banner.",
            format: "16:9 ratio, min 1280x720px (WebP or JPEG under 2MB).",
            webImpact: "Event card poster and full-bleed header background.",
          },
          {
            name: "Ticket Tier Name",
            type: "Text Input",
            required: true,
            description: "Label for the admission pass tier.",
            format: "e.g. 'Early Bird Regular', 'VIP Front Row', 'Table of 6'.",
            webImpact: "Listed on ticket selector during checkout.",
          },
          {
            name: "Ticket Price (₦)",
            type: "Number Input",
            required: true,
            description: "Cost per ticket in Nigerian Naira.",
            format: "Numeric integer (e.g. 15000 for ₦15,000). Enter 0 for Free passes.",
            webImpact: "Charged directly via Paystack gateway checkout.",
          },
          {
            name: "Tier Capacity Quota",
            type: "Number Input",
            required: true,
            description: "Total maximum tickets available to sell for this tier.",
            format: "Positive integer (e.g. 250).",
            webImpact: "Auto-disables purchase and displays 'Sold Out' when sold.",
          },
          {
            name: "Tier Badge / Tag",
            type: "Text Input",
            required: false,
            description: "Promotional badge attached to this tier.",
            format: "e.g. 'Best Value', 'Limited Capacity', 'VIP Access'. Max 20 chars.",
            webImpact: "Colored badge on the ticket selection card.",
          },
          {
            name: "Tier Features / Inclusions",
            type: "Bullet Point List",
            required: false,
            description: "Perks included with this ticket tier.",
            format: "e.g. ['Front Row Seating', 'Complimentary Drinks', 'Backstage Pass'].",
            webImpact: "Checklist of perks beneath the ticket price.",
          },
        ],
      },
    ],
  },
  {
    slug: "editorial-journal",
    pillarId: "creative-events",
    title: "Editorial Journal & Articles",
    badge: "Publishing & Media",
    readTime: "5 min read",
    targetAudience: ["Editorial Staff", "Writers", "Marketing"],
    summary:
      "Publish editorial thought pieces, artist spotlight interviews, event recaps, and industry insights on the Royz House Journal.",
    directAdminUrl: "/blog",
    clientWebPath: "/blog",
    webImpact: "Populates the public blog articles list, category tabs, and full reading pages.",
    quickReference: [
      { label: "Content Editor", value: "Rich text with headings, images, and quotes" },
      { label: "Categories", value: "Spotlights, Dance News, Music, Behind the Scenes" },
      { label: "Publishing Control", value: "Draft, Scheduled, Published" },
    ],
    sections: [
      {
        heading: "Article Editorial Form Fields",
        content:
          "Keep the Royz House community engaged with fresh stories, behind-the-scenes rehearsal coverage, and culture highlights.",
        steps: [
          "1. Open 'Blog' in the Admin sidebar.",
          "2. Click 'Write Article'.",
          "3. Input the Article Title and assign an Author.",
          "4. Select primary Category and estimated reading duration (e.g., '4 min read').",
          "5. Compose your story using the formatting tools (bold, bullet points, blockquotes).",
          "6. Upload a captivating cover image.",
          "7. Click 'Publish' to make the article live, or 'Save as Draft' to finish later.",
        ],
        fieldsTable: [
          {
            name: "Article Title",
            type: "Text Input",
            required: true,
            description: "Editorial headline for the article.",
            format: "Engaging headline (e.g. 'Behind the Scenes of the Afro-Futurism Showcase'). Max 120 chars.",
            webImpact: "Primary H1 headline on the article page and blog cards.",
          },
          {
            name: "Article Excerpt / Snippet",
            type: "Textarea",
            required: true,
            description: "Short introductory hook shown on article previews.",
            format: "1-2 sentences (max 180 chars).",
            webImpact: "Preview snippet on blog listing and social cards.",
          },
          {
            name: "Author Attribution",
            type: "Text Input / Select",
            required: true,
            description: "Writer or creative curator name.",
            format: "e.g. 'Royz Editorial Team' or 'Victor O.'.",
            webImpact: "Displayed alongside the publish date and read time.",
          },
          {
            name: "Article Category",
            type: "Select Dropdown",
            required: true,
            description: "Editorial topic classification.",
            format: "Options: 'Artist Spotlights', 'Culture & Dance', 'Music Reviews', 'Studio News'.",
            webImpact: "Category badge and filter tab on /blog.",
          },
          {
            name: "Reading Duration",
            type: "Text Input",
            required: false,
            description: "Estimated minutes to read the article.",
            format: "e.g. '4 min read'.",
            webImpact: "Displayed with clock icon on blog preview card.",
          },
          {
            name: "Cover Artwork",
            type: "Media Picker / Upload",
            required: true,
            description: "Main header artwork for the article.",
            format: "16:9 ratio, min 1200x675px WebP/JPEG.",
            webImpact: "Hero banner at top of article and thumbnail on cards.",
          },
          {
            name: "Article Body",
            type: "Rich Text / Markdown",
            required: true,
            description: "Full editorial content with formatted text, images, and quotes.",
            format: "Formatted headings (H2, H3), paragraphs, lists, blockquotes.",
            webImpact: "The full story rendered on the public reading page.",
          },
          {
            name: "Publication Status",
            type: "Select Dropdown",
            required: true,
            description: "Controls whether article is public or private.",
            format: "Options: 'Published' (Visible) or 'Draft' (Hidden).",
            webImpact: "Publishes or unpublishes the article instantly.",
          },
        ],
      },
    ],
  },
  {
    slug: "media-hub",
    pillarId: "creative-events",
    title: "Media Hub & Cloud Library",
    badge: "Digital Assets",
    readTime: "4 min read",
    targetAudience: ["Content Editors", "Videographers", "Marketing"],
    summary:
      "Manage photo galleries, video showcases, audition clips, and downloadable brand assets stored securely in the cloud.",
    directAdminUrl: "/media",
    clientWebPath: "/media",
    webImpact: "Powers media galleries, event photo albums, and video playback on the public site.",
    quickReference: [
      { label: "Supported Types", value: "JPEG, PNG, WebP, MP4, MP3, PDF" },
      { label: "Cloud Storage", value: "Global CDN for fast streaming" },
      { label: "Tagging", value: "Filter assets by event, artist, or production year" },
    ],
    sections: [
      {
        heading: "Cloud Media Upload Fields",
        content:
          "Centralize all high-resolution brand photography, showcase recordings, and artist press kits.",
        steps: [
          "1. Navigate to 'Media Content' in the Admin sidebar.",
          "2. Drag and drop your files into the upload dropzone or click 'Browse Files'.",
          "3. Add a descriptive title and tags (e.g., 'Winter Showcase 2026', 'Dance Rehearsal').",
          "4. Click 'Upload'. Once uploaded, you can copy the CDN URL or embed it directly into articles.",
        ],
        fieldsTable: [
          {
            name: "Asset File",
            type: "File Dropzone",
            required: true,
            description: "The media file to upload into cloud storage.",
            format: "Images (JPEG, PNG, WebP < 10MB), Audio (MP3 < 25MB), Video (MP4 < 100MB).",
            webImpact: "Uploaded to CDN and made available across the entire platform.",
          },
          {
            name: "Asset Title",
            type: "Text Input",
            required: true,
            description: "Human-readable label for the file.",
            format: "Descriptive name (e.g. 'Street Championship Finals 2026 - Stage Photo').",
            webImpact: "Image alt text and title caption in media galleries.",
          },
          {
            name: "Media Category",
            type: "Select Dropdown",
            required: true,
            description: "Asset bucket type.",
            format: "Options: 'Performance Photography', 'Showcase Video', 'Audio Track', 'Brand Kit'.",
            webImpact: "Filter bucket in the media library and public media hub.",
          },
          {
            name: "Tags / Keywords",
            type: "Tag Chips Input",
            required: false,
            description: "Search keywords associated with this asset.",
            format: "Comma-separated keywords (e.g. 'dance, stage, 2026, victor').",
            webImpact: "Enables instant search in the admin media picker.",
          },
        ],
      },
    ],
  },

  // PILLAR 4: OPERATIONS, FINANCE & INQUIRIES
  {
    slug: "donations-causes",
    pillarId: "operations-finance",
    title: "Donations, Giving Causes & Progress Bars",
    badge: "Fundraising & Philanthropy",
    readTime: "6 min read",
    targetAudience: ["Donations Managers", "Finance", "Foundation Directors"],
    summary:
      "Manage philanthropic giving causes, target fundraising goals in Naira (₦), real-time progress bars, and track donor contribution records verified through Paystack.",
    directAdminUrl: "/donations",
    clientWebPath: "/donate",
    webImpact:
      "Populates the donation cause selector, live dynamic progress bar, and preset chips on /donate.",
    quickReference: [
      { label: "Currency", value: "Nigerian Naira (₦)" },
      { label: "Preset Chips", value: "₦15,000 | ₦25,000 | ₦35,000 | ₦45,000" },
      { label: "Progress Bar", value: "Calculates live (Sum of approved records / Target Goal)" },
      { label: "Payment Verification", value: "Automated Paystack webhook & instant UI update" },
    ],
    sections: [
      {
        heading: "Campaign Cause Creation Fields",
        content:
          "Royz House empowers donors to contribute toward specific cultural causes (e.g., 'Youth Talent Scholarships', 'Creative Arts Studio Fund'). Each cause tracks a target goal and displays a live progress bar on the website.",
        steps: [
          "1. Go to 'Donations' in the Admin sidebar.",
          "2. Click the 'Campaigns' tab, then click 'Add Campaign / Cause'.",
          "3. Enter the Cause Title (e.g., 'Youth Performing Arts Fund').",
          "4. Write an inspiring description explaining what donations fund.",
          "5. Set the Target Goal Amount in Naira (₦) (e.g., 5000000 for ₦5,000,000).",
          "6. Set Status to 'Active'.",
          "7. Click 'Save Campaign'. The new cause appears immediately in the public donation form dropdown.",
        ],
        fieldsTable: [
          {
            name: "Cause Title",
            type: "Text Input",
            required: true,
            description: "The name of the philanthropic cause.",
            format: "Inspiring title (e.g. 'Youth Creative Arts Scholarship'). Max 80 chars.",
            webImpact: "Appears in the 'Select Cause' dropdown on /donate.",
          },
          {
            name: "Campaign Description",
            type: "Textarea",
            required: true,
            description: "Details on what the funds provide for creatives and students.",
            format: "1-2 paragraphs (max 400 chars).",
            webImpact: "Displayed beneath the cause selector when chosen by donor.",
          },
          {
            name: "Target Goal Amount (₦)",
            type: "Number Input",
            required: true,
            description: "Total funding target in Nigerian Naira.",
            format: "Numeric integer without punctuation (e.g. 5000000 for ₦5,000,000).",
            webImpact: "Denominator for the live dynamic progress bar on /donate.",
          },
          {
            name: "Campaign Status",
            type: "Select Dropdown",
            required: true,
            description: "Active status of the fundraising cause.",
            format: "Options: 'Active' (Available for donations) or 'Paused' (Temporarily closed).",
            webImpact: "Active causes show in donation form; paused causes are hidden.",
          },
        ],
        alert: {
          type: "tip",
          text: "The progress bar on the public website automatically updates as donations are verified through Paystack.",
        },
      },
    ],
  },
  {
    slug: "ticket-payments",
    pillarId: "operations-finance",
    title: "Ticket Orders & Financial Reconciliation",
    badge: "Commerce & Box Office",
    readTime: "5 min read",
    targetAudience: ["Box Office Managers", "Finance Staff", "Event Security"],
    summary:
      "View verified Paystack ticket transactions, audit customer orders in Naira (₦), export guest lists, and reconcile box office revenue.",
    directAdminUrl: "/payments",
    clientWebPath: "/events",
    webImpact: "Back-office financial audit. Confirms guest admissions and unlocks digital event tickets.",
    quickReference: [
      { label: "Gateway", value: "Paystack (PCI DSS Level 1 Certified)" },
      { label: "Reconciliation", value: "Automatic verification via payment reference" },
      { label: "Export", value: "Download CSV for door staff guest lists" },
    ],
    sections: [
      {
        heading: "Payment Audit & Guest List Controls",
        content:
          "When a patron purchases a ticket, their payment is verified through Paystack, and a booking record is immediately generated.",
        steps: [
          "1. Open 'Ticket Payments' in the Admin sidebar.",
          "2. Filter records by Event Name or date range.",
          "3. Review customer names, email addresses, quantity purchased, and tier.",
          "4. Use the Search Bar to look up a guest by Name, Email, or Paystack Reference.",
          "5. Click 'Export Guest List' to download an Excel/CSV file for check-in staff at the venue entrance.",
        ],
        fieldsTable: [
          {
            name: "Search Input",
            type: "Text Search Input",
            required: false,
            description: "Look up specific transactions or attendee tickets.",
            format: "Accepts Customer Name, Email, Ticket Code, or Paystack Reference.",
            webImpact: "Filters administrative records in real time.",
          },
          {
            name: "Event Filter",
            type: "Select Dropdown",
            required: false,
            description: "Filter orders for one specific showcase.",
            format: "List of all created events.",
            webImpact: "Allows isolating ticket sales for a specific night.",
          },
          {
            name: "Payment Status Filter",
            type: "Select Dropdown",
            required: false,
            description: "Filter transactions by settlement status.",
            format: "Options: 'All', 'Success', 'Abandoned', 'Failed'.",
            webImpact: "Verifies whether attendee is authorized for door entry.",
          },
          {
            name: "Export Guest List Action",
            type: "Button Action",
            required: false,
            description: "Exports filtered attendee roster to CSV spreadsheet.",
            format: "Downloads UTF-8 CSV containing Name, Tier, Ticket ID, and Barcode ref.",
            webImpact: "Used by physical security and front-of-house check-in personnel.",
          },
        ],
      },
    ],
  },
  {
    slug: "contact-inquiries",
    pillarId: "operations-finance",
    title: "Contact Inquiries Management",
    badge: "Customer Relations",
    readTime: "4 min read",
    targetAudience: ["Customer Care", "Operations Staff", "Reception"],
    summary:
      "Manage incoming messages submitted through the public website contact form, assign inquiry statuses, and reply to prospective partners.",
    directAdminUrl: "/contacts",
    clientWebPath: "/contact",
    webImpact: "Receives all messages submitted from the public /contact form in real time.",
    quickReference: [
      { label: "Statuses", value: "New, Under Review, Contacted, Resolved" },
      { label: "Notification", value: "Instant badge in the Admin sidebar" },
      { label: "Export", value: "CSV archive of all visitor inquiries" },
    ],
    sections: [
      {
        heading: "Inquiry Workflow & Moderation Fields",
        content:
          "Visitors submit messages regarding general inquiries, media partnerships, studio rentals, or feedback.",
        steps: [
          "1. Navigate to 'Contacts' -> 'Inquiries & Submissions' tab.",
          "2. Unread messages are marked with a 'New' badge.",
          "3. Click on any inquiry to read the full message and sender details.",
          "4. Change status to 'Under Review' or 'Contacted' as your team follows up.",
          "5. Once resolved, mark as 'Resolved' to keep the inbox organized.",
        ],
        fieldsTable: [
          {
            name: "Inquiry Status",
            type: "Select Dropdown",
            required: true,
            description: "Current operational processing state.",
            format: "Options: 'New' (Unread), 'Under Review', 'Contacted', 'Resolved'.",
            webImpact: "Updates badge and moves ticket through CRM pipeline.",
          },
          {
            name: "Internal Staff Notes",
            type: "Textarea",
            required: false,
            description: "Internal notes visible only to Royz House administrators.",
            format: "e.g. 'Followed up via phone on Oct 2nd, client agreed to proposal'.",
            webImpact: "Internal communication log between team members.",
          },
          {
            name: "Department Filter",
            type: "Select Dropdown",
            required: false,
            description: "Filter inquiries directed to a specific department.",
            format: "Options: 'All', 'General', 'Bookings', 'Press & Media'.",
            webImpact: "Routes messages to relevant department heads.",
          },
        ],
      },
    ],
  },
  {
    slug: "bookings-applications",
    pillarId: "operations-finance",
    title: "Talent Bookings & Join Applications",
    badge: "A&R & Booking Desk",
    readTime: "5 min read",
    targetAudience: ["A&R Team", "Talent Managers", "Executive Producers"],
    summary:
      "Review incoming private booking requests for Royz House artists, and vet new creatives who apply to join the house roster.",
    directAdminUrl: "/bookings",
    clientWebPath: "/talents",
    webImpact: "Processes booking requests from talent profiles and submissions from the 'Join Us' page.",
    quickReference: [
      { label: "Talent Bookings", value: "Corporate gigs, weddings, concerts, commercial shoots" },
      { label: "Audition Applications", value: "Dancers, choreographers, singers, musicians" },
      { label: "Review Status", value: "Pending, Shortlisted, Interview Scheduled, Approved, Archived" },
    ],
    sections: [
      {
        heading: "Talent Booking & Audition Review Fields",
        content:
          "When event organizers or corporate brands request to book a specific talent, their budget, dates, and event type arrive in the Bookings inbox.",
        steps: [
          "1. Go to 'Talent Bookings' in the Admin sidebar.",
          "2. Review the requested artist, client contact details, event date, and estimated budget.",
          "3. Contact the client to confirm availability and negotiate terms.",
          "4. Update booking status to 'Confirmed' or 'Declined'.",
        ],
        fieldsTable: [
          {
            name: "Booking Status",
            type: "Select Dropdown",
            required: true,
            description: "Status of the talent booking negotiation.",
            format: "Options: 'Pending', 'Negotiating', 'Confirmed', 'Declined'.",
            webImpact: "Tracks booking revenue and calendar availability.",
          },
          {
            name: "Agreed Fee (₦)",
            type: "Number Input",
            required: false,
            description: "Final negotiated compensation for the artist booking.",
            format: "Numeric integer in Naira (e.g. 450000 for ₦450,000).",
            webImpact: "Used for artist royalty payouts and agency commission.",
          },
          {
            name: "Audition Application Status",
            type: "Select Dropdown",
            required: true,
            description: "Status of prospective creative who submitted portfolio to join.",
            format: "Options: 'Pending Review', 'Shortlisted', 'Audition Scheduled', 'Accepted', 'Archived'.",
            webImpact: "Triggers automated notification email to the applicant.",
          },
          {
            name: "Audition Score & Notes",
            type: "Textarea",
            required: false,
            description: "A&R evaluation feedback on applicant's dance/vocal performance reel.",
            format: "Score 1-10 + comments on technical skill, stage presence, and attitude.",
            webImpact: "Internal evaluation record before offering roster contract.",
          },
        ],
      },
    ],
  },
  {
    slug: "newsletter-audience",
    pillarId: "operations-finance",
    title: "Newsletter Audience & CSV Exports",
    badge: "Audience & CRM",
    readTime: "3 min read",
    targetAudience: ["Marketing", "Community Managers"],
    summary:
      "Monitor subscriber growth from website footer signup forms and export clean email lists for Mailchimp, Brevo, or Klaviyo campaigns.",
    directAdminUrl: "/newsletter",
    clientWebPath: "/",
    webImpact: "Collects verified subscriber emails submitted via the website footer.",
    quickReference: [
      { label: "Export Format", value: "CSV (Comma Separated Values)" },
      { label: "Compatibility", value: "Mailchimp, Klaviyo, Brevo, Google Sheets" },
      { label: "Spam Protection", value: "Honeypot + rate-limiting active" },
    ],
    sections: [
      {
        heading: "Audience Management & Export Controls",
        content:
          "Keep your email marketing platforms synchronized with the latest subscribers.",
        steps: [
          "1. Go to 'Newsletter' in the Admin sidebar.",
          "2. View total active subscribers and sign-up dates.",
          "3. Click 'Export to CSV' to download the audience list.",
          "4. Import the file into your preferred email campaign provider.",
        ],
        fieldsTable: [
          {
            name: "Subscriber Email Address",
            type: "Email String",
            required: true,
            description: "The verified email entered into the footer newsletter form.",
            format: "Valid email (e.g. user@example.com).",
            webImpact: "Included in outgoing newsletter dispatches.",
          },
          {
            name: "Subscription Date",
            type: "Date-Time Timestamp",
            required: false,
            description: "Exact timestamp when visitor subscribed.",
            format: "Auto-recorded timestamp.",
            webImpact: "Enables segmenting by new vs. veteran subscribers.",
          },
          {
            name: "Subscriber Status",
            type: "Select Dropdown",
            required: true,
            description: "Subscription delivery status.",
            format: "Options: 'Active', 'Unsubscribed', 'Bounced'.",
            webImpact: "Ensures compliance with anti-spam privacy regulations.",
          },
        ],
      },
    ],
  },

  // PILLAR 5: SECURITY, ADMINISTRATION & SOPS
  {
    slug: "users-and-roles",
    pillarId: "governance-sops",
    title: "Admin Users, Roles & Permissions",
    badge: "Access Control",
    readTime: "5 min read",
    targetAudience: ["Super Administrators", "IT & Security", "Operations Directors"],
    summary:
      "Manage staff accounts, assign granular role permissions (Super Admin, Editor, Event Manager, Finance), and enforce security hygiene.",
    directAdminUrl: "/users-and-roles",
    clientWebPath: "/",
    webImpact: "Controls who has access to view, edit, or delete platform assets.",
    quickReference: [
      { label: "Super Admin", value: "Unrestricted access to all studios, users, and financials" },
      { label: "Content Editor", value: "Access to Homepage, About, Blog, Media, and Talents" },
      { label: "Event Manager", value: "Access to Events, Ticket Tiers, and Guest Lists" },
      { label: "Finance / Auditor", value: "Read-only access to Payments, Donations, and Reports" },
    ],
    sections: [
      {
        heading: "Staff Invitation & Role Assignment Fields",
        content:
          "Grant staff access strictly based on their job responsibilities following the principle of least privilege.",
        steps: [
          "1. Navigate to 'Users and Roles' in the Admin sidebar.",
          "2. Click 'Invite Admin User'.",
          "3. Enter the staff member's official corporate email address and full name.",
          "4. Select their role (Super Admin, Editor, Event Manager, or Viewer).",
          "5. Click 'Send Invitation'. The user receives an activation link to set their password.",
        ],
        fieldsTable: [
          {
            name: "Staff Full Name",
            type: "Text Input",
            required: true,
            description: "First and last name of the employee or contractor.",
            format: "e.g. 'Sarah Adeyemi'. Max 60 chars.",
            webImpact: "Displayed on the top bar and stamped onto audit log trails.",
          },
          {
            name: "Corporate Email Address",
            type: "Email Input",
            required: true,
            description: "Official staff email address used for login and notifications.",
            format: "Corporate domain preferred (e.g. sarah@royzhouz.com).",
            webImpact: "Receives activation link and security alerts.",
          },
          {
            name: "Role Assignment",
            type: "Select Dropdown",
            required: true,
            description: "Access level defining which studios the user can see and modify.",
            format: "Options: 'Super Admin', 'Content Editor', 'Event Manager', 'Finance / Auditor', 'Viewer'.",
            webImpact: "Enforces role-based route guards and permissions.",
          },
          {
            name: "Account Status",
            type: "Select / Toggle",
            required: true,
            description: "Active state of the administrative account.",
            format: "Options: 'Active', 'Suspended', 'Pending Activation'.",
            webImpact: "Instantly revokes or permits login access.",
          },
        ],
        alert: {
          type: "important",
          text: "Immediately revoke access for staff members who leave the organization by changing their account status to 'Suspended'.",
        },
      },
    ],
  },
  {
    slug: "security-audit-logs",
    pillarId: "governance-sops",
    title: "Security Audit Trails & Activity Logs",
    badge: "Compliance & Audit",
    readTime: "4 min read",
    targetAudience: ["Super Administrators", "Compliance", "Security"],
    summary:
      "Maintain strict regulatory accountability with an immutable log of every content change, ticket price adjustment, deletion, and role reassignment.",
    directAdminUrl: "/audit-logs",
    clientWebPath: "/",
    webImpact: "Internal regulatory and audit compliance tool.",
    quickReference: [
      { label: "Logged Events", value: "Create, Update, Delete, Publish, Status Change" },
      { label: "Metadata Captured", value: "Actor Name, Role, Timestamp, Resource Type, Old vs New Diff" },
      { label: "Immutability", value: "Audit records cannot be edited or erased by any user" },
    ],
    sections: [
      {
        heading: "Audit Trail Schema & Search Fields",
        content:
          "If a showcase ticket tier is accidentally altered or an article unpublished, the audit trail pinpoints precisely when the change occurred and who initiated it.",
        steps: [
          "1. Open 'Audit Logs' in the Admin sidebar.",
          "2. Filter by Resource (e.g., 'events', 'campaigns', 'site_settings').",
          "3. Expand any entry to view the exact payload change.",
        ],
        fieldsTable: [
          {
            name: "Actor (Admin User)",
            type: "User Identity",
            required: false,
            description: "The staff member who initiated the database change.",
            format: "Name, email, and IP address.",
            webImpact: "Accountability for operational updates.",
          },
          {
            name: "Action Type",
            type: "Action Code",
            required: false,
            description: "The specific operation performed.",
            format: "e.g. 'CREATE_EVENT', 'UPDATE_PRICE', 'DELETE_MEDIA', 'CHANGE_STATUS'.",
            webImpact: "Enables fast security categorization.",
          },
          {
            name: "Target Resource",
            type: "Resource String",
            required: false,
            description: "The database table or entity modified.",
            format: "e.g. 'events', 'ticket_tiers', 'site_settings', 'campaigns'.",
            webImpact: "Allows filtering activity by studio.",
          },
          {
            name: "Payload Diff",
            type: "JSON Before / After Object",
            required: false,
            description: "Exact snapshot comparing previous values to new values.",
            format: "Formatted JSON difference highlighting changed fields.",
            webImpact: "Facilitates instant rollback if a typo was published.",
          },
        ],
      },
    ],
  },
  {
    slug: "troubleshooting-sops",
    pillarId: "governance-sops",
    title: "Day-to-Day Staff SOPs & Troubleshooting",
    badge: "Operational Playbooks",
    readTime: "7 min read",
    targetAudience: ["All Team Members", "Event Staff", "Support Personnel"],
    summary:
      "Standard Operating Procedures (SOPs) for high-stakes events, ticket capacity increases, emergency announcements, and resolving common user questions.",
    directAdminUrl: "/",
    clientWebPath: "/",
    webImpact: "Guides staff through emergency updates, high-traffic ticket launches, and platform maintenance.",
    quickReference: [
      { label: "Pre-Showcase Checklist", value: "Verify capacity, flyer, ticket tier prices" },
      { label: "Emergency Notice", value: "Update Homepage Hero or Navigation Announcement" },
      { label: "Payment Questions", value: "Check Paystack reference in Ticket Payments tab" },
    ],
    sections: [
      {
        heading: "SOP 1: Pre-Launch Showcase Checklist",
        content:
          "Follow this mandatory 5-step checklist before opening ticket sales to the public:",
        steps: [
          "1. Confirm Venue & Schedule: Double-check start time and physical location in Events Studio.",
          "2. Validate Ticket Pricing in ₦: Ensure Regular (e.g. ₦5,000) and VIP (e.g. ₦20,000) are accurate.",
          "3. Verify Capacity Caps: Total tickets across all tiers must not exceed venue legal capacity.",
          "4. Test Live Web Preview: Open the public link in an incognito browser window.",
          "5. Announce Live Sales: Once published, share the direct link across official social channels.",
        ],
        fieldsTable: [
          {
            name: "Venue Capacity Check",
            type: "Verification Field",
            required: true,
            description: "Sum of all ticket tier quotas vs. venue fire marshal limit.",
            format: "Total regular + VIP + table seats <= hall capacity.",
            webImpact: "Prevents overcrowding and legal fines.",
          },
          {
            name: "Naira Currency Pricing Check",
            type: "Verification Field",
            required: true,
            description: "Confirmation that price was entered as integer Naira without extra zeros.",
            format: "e.g. '5000' for ₦5,000 (NOT '500000').",
            webImpact: "Prevents accidental 100x overcharging on customer bank cards.",
          },
          {
            name: "Paystack Gateway Verification",
            type: "Verification Field",
            required: true,
            description: "Confirming that checkout test payment verifies successfully.",
            format: "Live checkout modal opens, calculates total in ₦, and responds with success.",
            webImpact: "Guarantees attendees can complete ticket checkout smoothly.",
          },
        ],
      },
      {
        heading: "SOP 2: Resolving Attendee Payment Inquiries",
        content:
          "If a customer reports their card was debited but they haven't received confirmation:",
        steps: [
          "1. Request the customer's payment reference code from their bank debit alert or Paystack receipt.",
          "2. In Admin, navigate to 'Ticket Payments' and search the reference.",
          "3. If 'Success': Confirm their registered email address and resend the digital pass.",
          "4. If 'Abandoned / Failed': The transaction was declined by their bank. Advise them to retry with an alternate card.",
        ],
        alert: {
          type: "tip",
          text: "Always maintain polite and reassuring communication. Transactions failing on Paystack automatically refund within 24-48 hours per standard Nigerian banking rules.",
        },
      },
    ],
  },
];
