export { EventOverview } from "./EventOverview";
export { EventDetailHero } from "./EventDetailHero/EventDetailHero";
export { EventTicketSelector } from "./EventTicketSelector/EventTicketSelector";
export { EventAbout } from "./EventAbout/EventAbout";
export { EventSpeakers } from "./EventSpeakers/EventSpeakers";
export { EventSchedule } from "./EventSchedule/EventSchedule";
export { EventGallery } from "./EventGallery/EventGallery";
export { EventFAQ } from "./EventFAQ/EventFAQ";
export { EventSidebar } from "./EventSidebar/EventSidebar";
export { EventPopularEvents } from "./EventPopularEvents/EventPopularEvents";
export { PaymentSuccessModal, PaymentFailureModal } from "./PaymentModals";
