export const EVENT_CATEGORIES = [
  "All",
  "Summit",
  "Workshop",
  "Fashion Show",
  "Film Screening",
  "Concert",
];

export const EVENT_LOCATIONS = [
  "Nigeria",
  "Ghana",
  "Kenya",
  "South Africa",
  "Rwanda",
  "United Kingdom",
  "United States",
];

export const UPCOMING_EVENTS = [
  {
    id: "fashion-forward-abuja",
    slug: "fashion-forward-abuja",
    title: "Fashion Forward: Abuja",
    day: "08",
    month: "Oct",
    year: "2026",
    location: "National Diamond Centre, Abuja, Central",
    description: "Join Africa's premier fashion showcase highlighting creative innovation.",
    category: "Fashion Show",
    image: "/assets/img/events/events-hero-bg.png",
    ticketLink: "/events/fashion-forward-abuja",
    isPopular: false,
  },
  {
    id: "creative-summit-2026",
    slug: "creative-summit-2026",
    title: "Creative Summit 2026",
    day: "18",
    month: "Sep",
    year: "2026",
    location: "Eko Hotel & Suites, Lagos",
    description: "A gathering of creative minds shaping the future.",
    category: "Summit",
    image: "/assets/img/events/event1.jpg",
    ticketLink: "/events/creative-summit-2026",
    isPopular: false,
  },
  {
    id: "african-creatives-conference",
    slug: "african-creatives-conference",
    title: "African Creatives Conference",
    day: "26",
    month: "Sep",
    year: "2026",
    location: "Landmark Event Centre, Victoria Island, Lagos",
    description: "A gathering of creatives dedicated to shaping the future.",
    category: "Conferences",
    image: "/assets/img/events/event2.jpg",
    ticketLink: "/events/african-creatives-conference",
    isPopular: false,
  },
  {
    id: "royz-houz-music-arts-festival",
    slug: "royz-houz-music-arts-festival",
    title: "Royz Houz Music & Arts Festival",
    day: "10",
    month: "Oct",
    year: "2026",
    location: "Muson Centre, Onikan, Lagos",
    description: "A gathering of creatives dedicated to shaping the future.",
    category: "Concert",
    image: "/assets/img/events/events-hero-bg.png",
    ticketLink: "/events/royz-houz-music-arts-festival",
    isPopular: false,
  },
  {
    id: "future-of-african-creativity-terra",
    slug: "future-of-african-creativity-terra",
    title: "The Future of African Creativity",
    day: "24",
    month: "Oct",
    year: "2026",
    location: "Terra Kulture, Victoria Island, Lagos",
    description: "A gathering of creatives dedicated to shaping the future.",
    category: "Summit",
    image: "/assets/img/events/event2.jpg",
    ticketLink: "/events/future-of-african-creativity-terra",
    isPopular: false,
  },
  {
    id: "voices-of-the-next-generation",
    slug: "voices-of-the-next-generation",
    title: "Voices of the Next Generation",
    day: "14",
    month: "Nov",
    year: "2026",
    location: "The Nest Hub, Yaba, Lagos",
    description: "A gathering of creatives dedicated to shaping the future.",
    category: "Film Screening",
    image: "/assets/img/events/event3.jpg",
    ticketLink: "/events/voices-of-the-next-generation",
    isPopular: false,
  },
  {
    id: "creative-minds-networking-night",
    slug: "creative-minds-networking-night",
    title: "Creative Minds Networking Night",
    day: "05",
    month: "Dec",
    year: "2026",
    location: "Muri Okunola Park, VI, Lagos",
    description: "A gathering of creatives dedicated to shaping the future.",
    category: "Fashion Show",
    image: "/assets/img/impact.jpg",
    ticketLink: "/events/creative-minds-networking-night",
    isPopular: false,
  },
];

export const POPULAR_EVENTS = [
  {
    id: "pop-future-of-african-creativity",
    title: "The Future of African Creativity",
    day: "28",
    month: "Sep",
    year: "2026",
    location: "The Warehouse, Ikoyi, Lagos",
    description: "A gathering of creatives dedicated to shaping the future.",
    category: "Summit",
    image: "/assets/img/impact.jpg",
    ticketLink: "#",
    isPopular: true,
  },
  {
    id: "pop-the-next-generation-summit",
    title: "The Next Generation Summit",
    day: "15",
    month: "Oct",
    year: "2026",
    location: "Civic Centre, Victoria Island, Lagos",
    description: "A gathering of creatives dedicated to shaping the future.",
    category: "Summit",
    image: "/assets/img/events/event1.jpg",
    ticketLink: "#",
    isPopular: true,
  },
  {
    id: "pop-beyond-the-stage-live",
    title: "Beyond the Stage Live",
    day: "12",
    month: "Dec",
    year: "2026",
    location: "Radisson Blu Hotel, Ikeja, Lagos",
    description: "A gathering of creatives dedicated to shaping the future.",
    category: "Concert",
    image: "/assets/img/events/event3.jpg",
    ticketLink: "#",
    isPopular: true,
  },
];

export const PAST_EVENTS = [
  {
    id: "past-creative-summit-2022",
    slug: "past-creative-summit-2022",
    title: "Creative Summit 2022",
    category: "Summit",
    categoryTag: "PAST EVENTS",
    dateString: "November 2022 · Abuja, Nigeria",
    location: "Abuja, Nigeria",
    month: "Nov",
    year: "2022",
    day: "15",
    attendees: "3,400 attended",
    image: "/assets/img/events/event1.jpg",
    recapLink: "/events/past-creative-summit-2022",
    isPast: true,
  },
  {
    id: "past-creative-workshop-series-1",
    slug: "past-creative-workshop-series-1",
    title: "The Creative Workshop Series",
    category: "Workshop",
    categoryTag: "PAST EVENTS",
    dateString: "November 2022 · Abuja, Nigeria",
    location: "Abuja, Nigeria",
    month: "Nov",
    year: "2022",
    day: "20",
    attendees: "3,400 attended",
    image: "/assets/img/events/event2.jpg",
    recapLink: "/events/past-creative-workshop-series-1",
    isPast: true,
  },
  {
    id: "past-creative-workshop-series-2",
    slug: "past-creative-workshop-series-2",
    title: "The Creative Workshop Series",
    category: "Workshop",
    categoryTag: "PAST EVENTS",
    dateString: "November 2022 · Abuja, Nigeria",
    location: "Abuja, Nigeria",
    month: "Nov",
    year: "2022",
    day: "25",
    attendees: "3,400 attended",
    image: "/assets/img/events/event3.jpg",
    recapLink: "/events/past-creative-workshop-series-2",
    isPast: true,
  },
  {
    id: "past-film-night-vol-3",
    slug: "past-film-night-vol-3",
    title: "Film Night — Vol. 3",
    category: "Film Screening",
    categoryTag: "PAST EVENTS",
    dateString: "December 2020 · Abuja, Nigeria",
    location: "Abuja, Nigeria",
    month: "Dec",
    year: "2020",
    day: "12",
    attendees: "3,400 attended",
    image: "/assets/img/talents/upnext-new-beginnings.jpg",
    recapLink: "/events/past-film-night-vol-3",
    isPast: true,
  },
  {
    id: "past-creative-summit-2020",
    slug: "past-creative-summit-2020",
    title: "Creative Summit 2020",
    category: "Summit",
    categoryTag: "PAST EVENTS",
    dateString: "August 2020 · Rivers, Nigeria",
    location: "Rivers, Nigeria",
    month: "Aug",
    year: "2020",
    day: "18",
    attendees: "3,400 attended",
    image: "/assets/img/talents/producer-video-frame.jpg",
    recapLink: "/events/past-creative-summit-2020",
    isPast: true,
  },
  {
    id: "past-business-summit-2020",
    slug: "past-business-summit-2020",
    title: "Business Summit 2020",
    category: "Summit",
    categoryTag: "PAST EVENTS",
    dateString: "February 2020 · Abuja, Nigeria",
    location: "Abuja, Nigeria",
    month: "Feb",
    year: "2020",
    day: "10",
    attendees: "3,400 attended",
    image: "/assets/img/about/moments.jpg",
    recapLink: "/events/past-business-summit-2020",
    isPast: true,
  },
  {
    id: "past-royz-house-inaugural",
    slug: "past-royz-house-inaugural",
    title: "Royz House Inaugural Showcase",
    category: "Summit",
    categoryTag: "PAST EVENTS",
    dateString: "November 2020 · Lagos, Nigeria",
    location: "Lagos, Nigeria",
    month: "Nov",
    year: "2020",
    day: "08",
    attendees: "3,400 attended",
    image: "/assets/img/blog/blog1.jpg",
    recapLink: "/events/past-royz-house-inaugural",
    isPast: true,
  },
  {
    id: "past-creative-workshop-series-3",
    slug: "past-creative-workshop-series-3",
    title: "The Creative Workshop Series",
    category: "Summit",
    categoryTag: "PAST EVENTS",
    dateString: "September 2019 · Abuja, Nigeria",
    location: "Abuja, Nigeria",
    month: "Sep",
    year: "2019",
    day: "22",
    attendees: "3,400 attended",
    image: "/assets/img/events/events-hero-bg.png",
    recapLink: "/events/past-creative-workshop-series-3",
    isPast: true,
  },
  {
    id: "past-ai-empowered-generation",
    slug: "past-ai-empowered-generation",
    title: "Ai Empowered Generation Workshop",
    category: "Workshop",
    categoryTag: "PAST EVENTS",
    dateString: "January 2019 · Jos, Nigeria",
    location: "Jos, Nigeria",
    month: "Jan",
    year: "2019",
    day: "14",
    attendees: "3,400 attended",
    image: "/assets/img/talents/charles.jpg",
    recapLink: "/events/past-ai-empowered-generation",
    isPast: true,
  },
];

export const DEFAULT_EVENT_DETAILS = {
  id: "fashion-forward-abuja",
  slug: "fashion-forward-abuja",
  title: "Fashion Forward: Abuja",
  category: "Fashion Show",
  categoryTag: "FASHION SHOW",
  day: "08",
  month: "Oct",
  year: "2026",
  dateString: "October 8, 2026 · 10:00 PM",
  time: "10:00 PM",
  location: "National Diamond Centre, Abuja, Central",
  venue: "National Diamond Centre, Abuja, Central",
  heroImage: "/assets/img/events/events-hero-bg.png",
  image: "/assets/img/events/events-hero-bg.png",
  startingPrice: "₦45,000",
  ticketsSold: 75,
  totalTickets: 150,
  countdownTarget: "2026-10-08T22:00:00",
  aboutParagraphs: [
    "West Africa's premier fashion showcase spotlighting the continent's next generation of design talent. Full runway show, designer meet-and-greet, and pop-up market.",
    "Join Africa's most influential creative minds for a day of powerful keynotes, intimate workshops, live performances, and unparalleled networking. This summit is where culture meets commerce.",
  ],
  ticketTiers: [
    {
      id: "early-bird",
      name: "Early Bird",
      price: 45000,
      priceFormatted: "₦45,000",
      badge: "12 LEFT",
      badgeType: "alert",
      features: [
        "General access",
        "Welcome drink",
        "Event programme",
      ],
    },
    {
      id: "standard",
      name: "Standard",
      price: 85000,
      priceFormatted: "₦85,000",
      isDefault: true,
      features: [
        "General access",
        "Welcome drink",
        "Event programme",
        "Networking session",
      ],
    },
    {
      id: "vip",
      name: "VIP",
      price: 250000,
      priceFormatted: "₦250,000",
      badge: "8 LEFT",
      badgeType: "alert",
      features: [
        "Priority entry",
        "Backstage access",
        "Meet & greet",
        "Gift bag",
        "Reserved seating",
        "Post-event dinner",
      ],
    },
  ],
  speakers: [
    {
      id: "amara-osei",
      name: "Dr. Amara Osei",
      role: "Creative Economy Strategist",
      organization: "African Union",
      avatar: "/assets/img/events/speakers/amara.jpg",
    },
    {
      id: "fatima-diallo",
      name: "Fatima Diallo",
      role: "CEO",
      organization: "West Africa Fashion Week",
      avatar: "/assets/img/events/speakers/fatima.jpg",
    },
    {
      id: "kwame-asante",
      name: "Kwame Asante",
      role: "Film Director",
      organization: "Nile Studios",
      avatar: "/assets/img/events/speakers/kwame.jpg",
    },
    {
      id: "ngozi-williams",
      name: "Ngozi Williams",
      role: "Music Entrepreneur",
      organization: "AfroSound Records",
      avatar: "/assets/img/events/speakers/ngozi.jpg",
    },
  ],
  schedule: [
    { time: "16:00", title: "Warm - up and technique" },
    { time: "17:00", title: "Repertory building" },
    { time: "18:00", title: "Opening show" },
  ],
  gallery: [
    "/assets/img/events/gallery/gallery-1.jpg",
    "/assets/img/events/gallery/gallery-2.jpg",
    "/assets/img/events/gallery/gallery-3.jpg",
  ],
  venueMap: {
    name: "Kumasi Cultural Centre",
    address: "Kumasi Cultural Centre, Kumasi, Lagos",
    mapImage: "/assets/img/events/map-preview.png",
    googleMapsUrl: "https://maps.google.com/?q=Kumasi+Cultural+Centre+Lagos",
  },
  faqs: [
    {
      question: "What's the dress code?",
      answer:
        "The dress code is Creative Black Tie / High Fashion. Guests are encouraged to celebrate African contemporary elegance.",
    },
    {
      question: "Can I transfer my ticket?",
      answer:
        "Yes, ticket transfers are permitted up to 48 hours before the event start time through your account portal or support.",
    },
    {
      question: "Is parking available?",
      answer:
        "Yes, dedicated on-site secure parking is available for all attendees, with valet services complimentary for VIP ticket holders.",
    },
    {
      question: "Will sessions be recorded?",
      answer:
        "Select keynote sessions and runway highlights will be recorded and shared with registered attendees following the event.",
    },
    {
      question: "What is the refund policy?",
      answer:
        "Tickets are refundable up to 7 days before the event date. After this period, tickets may be transferred to another attendee.",
    },
  ],
  host: {
    name: "Zara Diallo",
    role: "Lead Stylist & Creative Director",
    avatar: "/assets/img/talents/zara.jpg",
  },
  partners: [
    "Unity Bank",
    "TechHive",
    "ArtsFund",
    "MediaCo",
    "StyleNG",
    "CreativeX",
  ],
  performingArtists: [
    {
      id: "zara-diallo",
      name: "Zara Diallo",
      initial: "Z",
      href: "/talents/zara-diallo",
    },
  ],
  tags: ["Fashion", "Design", "Abuja", "Runway", "Social", "Festival"],
};

export const POPULAR_CALENDAR_EVENTS = [
  {
    id: "pop-creative-summit-24-may",
    slug: "creative-summit-2026",
    title: "Creative Summit 2026",
    day: "24",
    month: "May",
    year: "2026",
    location: "Eko Hotel & Suites, Lagos",
    image: "/assets/img/events/event1.jpg",
    ticketLink: "/events/creative-summit-2026",
  },
  {
    id: "pop-creative-summit-15-june",
    slug: "creative-summit-2026",
    title: "Creative Summit 2026",
    day: "15",
    month: "June",
    year: "2026",
    location: "Eko Hotel & Suites, Lagos",
    image: "/assets/img/events/event2.jpg",
    ticketLink: "/events/creative-summit-2026",
  },
];


