export const EVENT_CATEGORIES = [
  "All",
  "Summit",
  "Workshop",
  "Fashion Show",
  "Film Screening",
  "Concert",
];

export const EVENT_LOCATIONS = [
  "Nigeria",
  "Ghana",
  "Kenya",
  "South Africa",
  "Rwanda",
  "United Kingdom",
  "United States",
];

export const UPCOMING_EVENTS = [
  {
    id: "creative-summit-2026",
    title: "Creative Summit 2026",
    day: "18",
    month: "Sep",
    year: "2026",
    location: "Eko Hotel & Suites, Lagos",
    description: "A gathering of creative minds shaping the future.",
    category: "Summit",
    image: "/assets/img/events/event1.jpg",
    ticketLink: "#",
    isPopular: false,
  },
  {
    id: "african-creatives-conference",
    title: "African Creatives Conference",
    day: "26",
    month: "Sep",
    year: "2026",
    location: "Landmark Event Centre, Victoria Island, Lagos",
    description: "A gathering of creatives dedicated to shaping the future.",
    category: "Conferences",
    image: "/assets/img/events/event2.jpg",
    ticketLink: "#",
    isPopular: false,
  },
  {
    id: "royz-houz-music-arts-festival",
    title: "Royz Houz Music & Arts Festival",
    day: "10",
    month: "Oct",
    year: "2026",
    location: "Muson Centre, Onikan, Lagos",
    description: "A gathering of creatives dedicated to shaping the future.",
    category: "Concert",
    image: "/assets/img/events/events-hero-bg.png",
    ticketLink: "#",
    isPopular: false,
  },
  {
    id: "future-of-african-creativity-terra",
    title: "The Future of African Creativity",
    day: "24",
    month: "Oct",
    year: "2026",
    location: "Terra Kulture, Victoria Island, Lagos",
    description: "A gathering of creatives dedicated to shaping the future.",
    category: "Summit",
    image: "/assets/img/events/event2.jpg",
    ticketLink: "#",
    isPopular: false,
  },
  {
    id: "voices-of-the-next-generation",
    title: "Voices of the Next Generation",
    day: "14",
    month: "Nov",
    year: "2026",
    location: "The Nest Hub, Yaba, Lagos",
    description: "A gathering of creatives dedicated to shaping the future.",
    category: "Film Screening",
    image: "/assets/img/events/event3.jpg",
    ticketLink: "#",
    isPopular: false,
  },
  {
    id: "creative-minds-networking-night",
    title: "Creative Minds Networking Night",
    day: "05",
    month: "Dec",
    year: "2026",
    location: "Muri Okunola Park, VI, Lagos",
    description: "A gathering of creatives dedicated to shaping the future.",
    category: "Fashion Show",
    image: "/assets/img/impact.jpg",
    ticketLink: "#",
    isPopular: false,
  },
];

export const POPULAR_EVENTS = [
  {
    id: "pop-future-of-african-creativity",
    title: "The Future of African Creativity",
    day: "28",
    month: "Sep",
    year: "2026",
    location: "The Warehouse, Ikoyi, Lagos",
    description: "A gathering of creatives dedicated to shaping the future.",
    category: "Summit",
    image: "/assets/img/impact.jpg",
    ticketLink: "#",
    isPopular: true,
  },
  {
    id: "pop-the-next-generation-summit",
    title: "The Next Generation Summit",
    day: "15",
    month: "Oct",
    year: "2026",
    location: "Civic Centre, Victoria Island, Lagos",
    description: "A gathering of creatives dedicated to shaping the future.",
    category: "Summit",
    image: "/assets/img/events/event1.jpg",
    ticketLink: "#",
    isPopular: true,
  },
  {
    id: "pop-beyond-the-stage-live",
    title: "Beyond the Stage Live",
    day: "12",
    month: "Dec",
    year: "2026",
    location: "Radisson Blu Hotel, Ikeja, Lagos",
    description: "A gathering of creatives dedicated to shaping the future.",
    category: "Concert",
    image: "/assets/img/events/event3.jpg",
    ticketLink: "#",
    isPopular: true,
  },
];

export const PAST_EVENTS = [
  {
    id: "past-creative-summit-2022",
    title: "Creative Summit 2022",
    category: "Summit",
    categoryTag: "SUMMIT",
    dateString: "November 2022 · Abuja, Nigeria",
    location: "Abuja, Nigeria",
    month: "Nov",
    year: "2022",
    day: "15",
    attendees: "3,400 attended",
    image: "/assets/img/events/event1.jpg",
    recapLink: "#",
    isPast: true,
  },
  {
    id: "past-creative-workshop-series-1",
    title: "The Creative Workshop Series",
    category: "Workshop",
    categoryTag: "WORKSHOP",
    dateString: "November 2022 · Abuja, Nigeria",
    location: "Abuja, Nigeria",
    month: "Nov",
    year: "2022",
    day: "20",
    attendees: "3,400 attended",
    image: "/assets/img/events/event2.jpg",
    recapLink: "#",
    isPast: true,
  },
  {
    id: "past-creative-workshop-series-2",
    title: "The Creative Workshop Series",
    category: "Workshop",
    categoryTag: "WORKSHOP",
    dateString: "November 2022 · Abuja, Nigeria",
    location: "Abuja, Nigeria",
    month: "Nov",
    year: "2022",
    day: "25",
    attendees: "3,400 attended",
    image: "/assets/img/events/event3.jpg",
    recapLink: "#",
    isPast: true,
  },
  {
    id: "past-film-night-vol-3",
    title: "Film Night — Vol. 3",
    category: "Film Screening",
    categoryTag: "FILM NIGHT",
    dateString: "December 2020 · Abuja, Nigeria",
    location: "Abuja, Nigeria",
    month: "Dec",
    year: "2020",
    day: "12",
    attendees: "3,400 attended",
    image: "/assets/img/talents/upnext-new-beginnings.jpg",
    recapLink: "#",
    isPast: true,
  },
  {
    id: "past-creative-summit-2020",
    title: "Creative Summit 2020",
    category: "Summit",
    categoryTag: "SUMMIT",
    dateString: "August 2020 · Rivers, Nigeria",
    location: "Rivers, Nigeria",
    month: "Aug",
    year: "2020",
    day: "18",
    attendees: "3,400 attended",
    image: "/assets/img/talents/producer-video-frame.jpg",
    recapLink: "#",
    isPast: true,
  },
  {
    id: "past-business-summit-2020",
    title: "Business Summit 2020",
    category: "Summit",
    categoryTag: "SUMMIT",
    dateString: "February 2020 · Abuja, Nigeria",
    location: "Abuja, Nigeria",
    month: "Feb",
    year: "2020",
    day: "10",
    attendees: "3,400 attended",
    image: "/assets/img/about/moments.jpg",
    recapLink: "#",
    isPast: true,
  },
  {
    id: "past-royz-house-inaugural",
    title: "Royz House Inaugural Showcase",
    category: "Summit",
    categoryTag: "SUMMIT",
    dateString: "November 2020 · Lagos, Nigeria",
    location: "Lagos, Nigeria",
    month: "Nov",
    year: "2020",
    day: "08",
    attendees: "3,400 attended",
    image: "/assets/img/blog/blog1.jpg",
    recapLink: "#",
    isPast: true,
  },
  {
    id: "past-creative-workshop-series-3",
    title: "The Creative Workshop Series",
    category: "Summit",
    categoryTag: "SUMMIT",
    dateString: "September 2019 · Abuja, Nigeria",
    location: "Abuja, Nigeria",
    month: "Sep",
    year: "2019",
    day: "22",
    attendees: "3,400 attended",
    image: "/assets/img/events/events-hero-bg.png",
    recapLink: "#",
    isPast: true,
  },
  {
    id: "past-ai-empowered-generation",
    title: "Ai Empowered Generation Workshop",
    category: "Workshop",
    categoryTag: "WORKSHOP",
    dateString: "January 2019 · Jos, Nigeria",
    location: "Jos, Nigeria",
    month: "Jan",
    year: "2019",
    day: "14",
    attendees: "3,400 attended",
    image: "/assets/img/talents/charles.jpg",
    recapLink: "#",
    isPast: true,
  },
];

