/**
 * Featured Talents Data (for Home Page — 8 Featured Talents)
 */
export const FEATURED_TALENTS = [
  {
    id: "julius-ayomide",
    slug: "julius-ayomide",
    name: "Julius Ayomide",
    category: "INFLUENCER",
    genre: "Afrobeats / R&B",
    location: "Lagos, Nigeria",
    rating: "4.9",
    followers: "125K",
    image: "/assets/img/talents/julius.jpg",
    isHot: true,
  },
  {
    id: "zara-diallo",
    slug: "zara-diallo",
    name: "Zara Diallo",
    category: "WRITER",
    genre: "Afrobeats / R&B",
    location: "Lagos, Nigeria",
    rating: "4.9",
    followers: "125K",
    image: "/assets/img/talents/zara.jpg",
    isHot: true,
  },
  {
    id: "fatima-ibrahim",
    slug: "fatima-ibrahim",
    name: "Fatima ibrahim",
    category: "DANCER",
    genre: "Afrobeats / R&B",
    location: "Lagos, Nigeria",
    rating: "4.9",
    followers: "125K",
    image: "/assets/img/talents/fatima.jpg",
    isHot: true,
  },
  {
    id: "kenneth-davis",
    slug: "kenneth-davis",
    name: "Kenneth Davis",
    category: "MUSICIAN",
    genre: "Afrobeats / R&B",
    location: "Abuja, Nigeria",
    rating: "4.9",
    followers: "125K",
    image: "/assets/img/talents/amara.jpg",
    isHot: true,
  },
  {
    id: "emeka-nwosu",
    slug: "emeka-nwosu",
    name: "Emeka Nwosu",
    category: "PRODUCER",
    genre: "Afrobeats / R&B",
    location: "Lagos, Nigeria",
    rating: "4.9",
    followers: "125K",
    image: "/assets/img/talents/emeka.jpg",
    isHot: true,
  },
  {
    id: "blessing-moses",
    slug: "blessing-moses",
    name: "Blessing Moses",
    category: "DESIGNER",
    genre: "Afrobeats / R&B",
    location: "Lagos, Nigeria",
    rating: "4.9",
    followers: "125K",
    image: "/assets/img/talents/blessing.jpg",
    isHot: true,
  },
  {
    id: "jenny-donald",
    slug: "jenny-donald",
    name: "Jenny Donald",
    category: "ACTOR",
    genre: "Afrobeats / R&B",
    location: "Abuja, Nigeria",
    rating: "4.9",
    followers: "125K",
    image: "/assets/img/talents/kofi.jpg",
    isHot: true,
  },
  {
    id: "charles-moses",
    slug: "charles-moses",
    name: "Charles Moses",
    category: "MUSICIAN",
    genre: "Afrobeats / R&B",
    location: "Abuja, Nigeria",
    rating: "4.9",
    followers: "125K",
    image: "/assets/img/talents/charles.jpg",
    isHot: true,
  },
];

/**
 * Trending Talents Data (for Talents Page /talent-hub)
 */
export const TRENDING_TALENTS = [
  {
    id: "amara-nwosu",
    slug: "amara-nwosu",
    name: "Amara Nwosu",
    profession: "Musician",
    image: "/assets/img/talents/amara.jpg",
    alt: "Amara Nwosu - Musician",
  },
  {
    id: "zara-diallo",
    slug: "zara-diallo",
    name: "Zara Diallo",
    profession: "Dancer",
    image: "/assets/img/talents/zara.jpg",
    alt: "Zara Diallo - Dancer",
  },
  {
    id: "julius-ayomide",
    slug: "julius-ayomide",
    name: "Julius Ayomide",
    profession: "Actor",
    image: "/assets/img/talents/julius.jpg",
    alt: "Julius Ayomide - Actor",
  },
  {
    id: "fatima-ibrahim",
    slug: "fatima-ibrahim",
    name: "Fatima Ibrahim",
    profession: "Writer",
    image: "/assets/img/talents/fatima.jpg",
    alt: "Fatima Ibrahim - Writer",
  },
];

/**
 * Talent Directory Categories Filter
 */
export const TALENT_CATEGORIES = [
  { id: "all", label: "All" },
  { id: "musicians", label: "Musicians" },
  { id: "actors", label: "Actors" },
  { id: "producers", label: "Producers" },
  { id: "dancers", label: "Dancers" },
  { id: "influencers", label: "Influencers" },
  { id: "writers", label: "Writers" },
];

/**
 * Comprehensive Talent Directory and Detail Profiles
 */
export const TALENT_DIRECTORY_ITEMS = [
  // 1. PRODUCER — Julius Ayomide
  {
    id: "julius-ayomide",
    slug: "julius-ayomide",
    name: "Julius Ayomide",
    category: "PRODUCER",
    categoryKey: "producers",
    badge: "PRODUCER",
    subtitle: "Producer / Drama / Romance — Enugu, Nigeria",
    bio: "Julius Ayomide is a creative music producer and beatmaker from Ebonyi State, Nigeria, specializing in Afrobeats, Hip-Hop, and contemporary African sounds. His productions combine layered percussion, melodic instrumentation, and modern textures to create distinctive sounds for emerging and established artists. Julius is particularly passionate about helping artists transform simple musical ideas into polished records that reflect their individual identity and creative direction. His growing body of work continues to establish him as a promising voice in African production.",
    rating: "4.9",
    reviewCount: 4.9,
    followers: "210K",
    bookingPrice: "₦600,000",
    image: "/assets/img/talents/julius.jpg",
    coverImage: "/assets/img/talents/producer-hero.jpg",
    isHot: true,
    tabs: ["ABOUT", "GALLERY", "VIDEOS", "MUSIC"],
    awards: [
      "African Music Award Nominee 2023",
      "Best New Artist — Lagos Sound Fest",
      "Royz House Excellence Award",
    ],
    achievements: [
      "Performed at AFRIMMA 2023",
      "Featured on BBC Africa",
      "4M+ streams on debut EP",
      "Brand ambassador — Lagos Fashion Week",
    ],
    musicTracks: [
      {
        id: "golden-hour",
        title: "Golden Hour",
        plays: "1.2M Plays",
        streams: "1.2M",
        duration: "3:42",
      },
      {
        id: "agba-woman",
        title: "Agba Woman",
        plays: "980K Plays",
        streams: "980K",
        duration: "3:28",
      },
      {
        id: "soulfire",
        title: "Soulfire",
        plays: "750K Plays",
        streams: "750K",
        duration: "3:28",
      },
      {
        id: "lagos-nights",
        title: "Lagos Nights",
        plays: "612K Plays",
        streams: "612K",
        duration: "4:18",
      },
      {
        id: "california-sunset-night",
        title: "California Sunset Night",
        plays: "612K Plays",
        streams: "612K",
        duration: "4:18",
      },
    ],
    socials: {
      facebook: "https://facebook.com",
      youtube: "https://youtube.com",
      instagram: "https://instagram.com",
      twitter: "https://twitter.com",
      tiktok: "https://tiktok.com",
    },
    videoReel: {
      id: "the-sound-architect",
      title: "The Sound Architect",
      thumbnail: "/assets/img/talents/producer-hero.jpg",
      portfolioTitle: "Production Credits — Julius Ayomide",
      portfolioBadge: "4 productions",
      portfolioItems: [
        {
          id: 1,
          title: "One Africa",
          subtitle: "Produced by Julius Ayomide • 980K plays",
          duration: "3:42",
          isActive: true,
        },
        {
          id: 2,
          title: "Vibes & Patterns",
          subtitle: "Produced by Julius Ayomide • 1.2M plays",
          duration: "4:01",
        },
        {
          id: 3,
          title: "No Pressure",
          subtitle: "Produced by Julius Ayomide • 756K plays",
          duration: "3:28",
        },
        {
          id: 4,
          title: "Midnight Calling",
          subtitle: "Produced by Julius Ayomide • 512K plays",
          duration: "4:18",
        },
      ],
      upNextVideos: [
        {
          id: "golden-hour",
          title: "Golden Hour",
          artist: "Amaka Nwosu",
          duration: "4 : 01",
          thumbnail: "/assets/img/talents/upnext-golden-hour.jpg",
          href: "/talents/julius-ayomide/video/golden-hour",
        },
        {
          id: "beautiful-chaos",
          title: "Beautiful Chaos",
          artist: "Tee Brown",
          duration: "3 : 28",
          thumbnail: "/assets/img/talents/upnext-beautiful-chaos.jpg",
          href: "/talents/julius-ayomide/video/beautiful-chaos",
        },
        {
          id: "new-beginnings",
          title: "New Beginnings",
          artist: "Ayo Kalu",
          duration: "4 : 18",
          thumbnail: "/assets/img/talents/upnext-new-beginnings.jpg",
          href: "/talents/julius-ayomide/video/new-beginnings",
        },
      ],
    },
    relatedCategoryTitle: "More Producers",
    relatedCreatives: [
      {
        id: "peace-ojo",
        name: "Peace Ojo",
        category: "Producer",
        image: "/assets/img/talents/studio.jpg",
        slug: "peace-ojo",
      },
      {
        id: "janet-obi",
        name: "Janet Obi",
        category: "Producer",
        image: "/assets/img/talents/headphones.jpg",
        slug: "janet-obi",
      },
      {
        id: "joshua-adeyemi",
        name: "Joshua Adeyemi",
        category: "Producer",
        image: "/assets/img/talents/emeka.jpg",
        slug: "joshua-adeyemi",
      },
    ],
  },

  // 2. MUSICIAN — Zara Diallo
  {
    id: "zara-diallo",
    slug: "zara-diallo",
    name: "Zara Diallo",
    category: "MUSICIAN",
    categoryKey: "musicians",
    badge: "MUSIC",
    subtitle: "Afrobeats / R&B — Lagos, Nigeria",
    bio: "Zara Diallo is an emerging Afro-pop and R&B vocalist from Lagos, Nigeria, known for her warm vocals, heartfelt lyrics, and vibrant stage presence.",
    rating: "4.9",
    reviewCount: 4.9,
    followers: "125K followers",
    bookingPrice: "₦250,000",
    image: "/assets/img/talents/zara.jpg",
    coverImage: "/assets/img/talents/amara.jpg",
    isHot: true,
    tabs: ["ABOUT", "GALLERY", "VIDEOS", "MUSIC"],
    awards: [
      "African Music Award Nominee 2023",
      "Best New Artist — Lagos Sound Fest",
      "Royz House Excellence Award",
    ],
    achievements: [
      "Released debut EP After the Rain",
      "Performed at Enugu Arts & Culture Festival",
      "Surpassed 500K combined streams",
      "Featured on three emerging-artist playlists",
    ],
    socials: {
      facebook: "https://facebook.com",
      youtube: "https://youtube.com",
      instagram: "https://instagram.com",
      twitter: "https://twitter.com",
      tiktok: "https://tiktok.com",
    },
    musicTracks: [
      { id: "golden-hour", title: "Golden Hour", duration: "3:42", plays: "1.2M plays", streams: "1.2M" },
      { id: "agba-woman", title: "Agba Woman", duration: "4:01", plays: "980K plays", streams: "980K" },
      { id: "soulfire", title: "Soulfire", duration: "3:28", plays: "756K plays", streams: "756K" },
      { id: "lagos-nights", title: "Lagos Nights", duration: "4:18", plays: "612K plays", streams: "612K" },
    ],
    videoReel: {
      id: "golden-hour",
      title: "Golden Hour",
      thumbnail: "/assets/img/talents/zara.jpg",
      portfolioTitle: "Playlist — Zara Diallo",
      portfolioBadge: "4 tracks",
      portfolioItems: [
        {
          id: 1,
          title: "Golden Hour",
          subtitle: "1.2M plays",
          duration: "3:42",
          isActive: true,
        },
        {
          id: 2,
          title: "Agba Woman",
          subtitle: "980K plays",
          duration: "4:01",
        },
        {
          id: 3,
          title: "Soulfire",
          subtitle: "756K plays",
          duration: "3:28",
        },
        {
          id: 4,
          title: "Lagos Nights",
          subtitle: "612K plays",
          duration: "4:18",
        },
      ],
      upNextVideos: [
        {
          id: "agba-woman",
          title: "Agba Woman",
          artist: "Amaka Nwosu · 980K",
          duration: "4 : 01",
          thumbnail: "/assets/img/talents/upnext-golden-hour.jpg",
          href: "/talents/zara-diallo/video/agba-woman",
        },
        {
          id: "soulfire",
          title: "Soulfire",
          artist: "Tee Brown · 756K",
          duration: "3 : 28",
          thumbnail: "/assets/img/talents/upnext-beautiful-chaos.jpg",
          href: "/talents/zara-diallo/video/soulfire",
        },
        {
          id: "lagos-nights",
          title: "Lagos Nights",
          artist: "Amaka Nwosu · 612K",
          duration: "4 : 18",
          thumbnail: "/assets/img/talents/upnext-new-beginnings.jpg",
          href: "/talents/zara-diallo/video/lagos-nights",
        },
      ],
    },
    relatedCategoryTitle: "More Creatives",
    relatedCreatives: [
      {
        id: "blessing-moses",
        name: "Blessing Moses",
        category: "Musician",
        image: "/assets/img/talents/blessing.jpg",
        slug: "blessing-moses",
      },
      {
        id: "amaka-nwosu",
        name: "Amaka Nwosu",
        category: "Musician",
        image: "/assets/img/talents/amara.jpg",
        slug: "amaka-nwosu",
      },
      {
        id: "tee-brown",
        name: "Tee Brown",
        category: "Musician",
        image: "/assets/img/talents/emeka.jpg",
        slug: "tee-brown",
      },
    ],
  },

  // 3. ACTOR — Jenny Donald
  {
    id: "jenny-donald",
    slug: "jenny-donald",
    name: "Jenny Donald",
    category: "ACTOR",
    categoryKey: "actors",
    badge: "ACTOR",
    subtitle: "Drama / Film — Imo, Nigeria",
    bio: "Jenny Donald is a versatile Nigerian actress known for her emotionally grounded performances and ability to bring complex characters to life.",
    rating: "4.9",
    reviewCount: 4.9,
    followers: "125K followers",
    bookingPrice: "₦250,000",
    image: "/assets/img/talents/kofi.jpg",
    coverImage: "/assets/img/talents/kofi.jpg",
    isHot: true,
    tabs: ["ABOUT", "GALLERY", "VIDEOS"],
    awards: [
      "Best Emerging Actor — Southeast Film Awards 2025",
      "Best Actor Nominee — Nigerian Independent Film Festival",
    ],
    achievements: [
      "Featured in 12+ short and independent films",
      "Played lead roles in three emerging film projects",
      "Performed in 8 stage productions",
      "Featured at two Nigerian film festivals",
    ],
    socials: {
      facebook: "https://facebook.com",
      youtube: "https://youtube.com",
      instagram: "https://instagram.com",
      twitter: "https://twitter.com",
      tiktok: "https://tiktok.com",
    },
    videoReel: {
      id: "acting-showreel",
      title: "Acting Showreel",
      thumbnail: "/assets/img/talents/kofi.jpg",
      portfolioTitle: "Filmography — Jenny Donald",
      portfolioBadge: "4 dramas",
      portfolioItems: [
        {
          id: 1,
          title: "The Last Promise",
          subtitle: "Lead Actress · Drama",
          duration: "3:28",
        },
        {
          id: 2,
          title: "Shadows of Home",
          subtitle: "Supporting Actress · Romance",
          duration: "3:42",
          isActive: true,
        },
        {
          id: 3,
          title: "Between Two Worlds",
          subtitle: "Lead Actress · Drama",
          duration: "4:01",
        },
        {
          id: 4,
          title: "Lagos A New Beginning",
          subtitle: "Supporting Actress · Film",
          duration: "4:18",
        },
      ],
      upNextVideos: [
        {
          id: "the-last-promise",
          title: "The Last Promise",
          artist: "Official Trailer",
          duration: "4 : 01",
          thumbnail: "/assets/img/talents/upnext-golden-hour.jpg",
          href: "/talents/jenny-donald/video/the-last-promise",
        },
        {
          id: "shadows-of-home",
          title: "Shadows of Home",
          artist: "Featured Scene",
          duration: "3 : 28",
          thumbnail: "/assets/img/talents/upnext-beautiful-chaos.jpg",
          href: "/talents/jenny-donald/video/shadows-of-home",
        },
        {
          id: "between-two-worlds",
          title: "Between Two Worlds",
          artist: "Jenny's Best Scene",
          duration: "4 : 18",
          thumbnail: "/assets/img/talents/upnext-new-beginnings.jpg",
          href: "/talents/jenny-donald/video/between-two-worlds",
        },
      ],
    },
    relatedCategoryTitle: "More Actors",
    relatedCreatives: [
      {
        id: "daniel-nwosu",
        name: "Daniel Nwosu",
        category: "Actor · Drama / Film",
        image: "/assets/img/talents/studio.jpg",
        slug: "daniel-nwosu",
      },
      {
        id: "amaka-eze",
        name: "Amaka Eze",
        category: "Actress · Drama / Romance",
        image: "/assets/img/talents/amara.jpg",
        slug: "amaka-eze",
      },
      {
        id: "ibrahim-garba",
        name: "Ibrahim Garba",
        category: "Actor · Action / Drama",
        image: "/assets/img/talents/headphones.jpg",
        slug: "ibrahim-garba",
      },
    ],
  },

  // 4. DANCER — Favour Ekanem
  {
    id: "favour-ekanem",
    slug: "favour-ekanem",
    name: "Favour Ekanem",
    category: "DANCER",
    categoryKey: "dancers",
    badge: "DANCE",
    subtitle: "Dancer · Afro-contemporary / Traditional · Akwa Ibom, Nigeria",
    bio: "Favour Ekanem is a talented dancer and performer from Akwa Ibom, Nigeria, known for blending contemporary movement with traditional Nigerian dance.",
    rating: "4.9",
    reviewCount: 4.9,
    followers: "164K followers",
    bookingPrice: "₦250,000",
    image: "/assets/img/talents/fatima.jpg",
    coverImage: "/assets/img/talents/fatima.jpg",
    isHot: true,
    tabs: ["ABOUT", "GALLERY", "VIDEOS"],
    awards: [
      "Best Contemporary Dancer — Lagos Dance Awards 2025",
      "Choreographer of the Year Nominee",
      "Royz Houz Creative Excellence Award",
    ],
    achievements: [
      "Performed at 25+ cultural and entertainment events",
      "Featured in three national dance showcases",
      "Choreographed 10+ stage and music productions",
      "Trained over 40 emerging dancers through workshops",
    ],
    socials: {
      facebook: "https://facebook.com",
      youtube: "https://youtube.com",
      instagram: "https://instagram.com",
      twitter: "https://twitter.com",
      tiktok: "https://tiktok.com",
    },
    videoReel: {
      id: "performance-portfolio",
      title: "Performance Portfolio — Favour Ekanem",
      subtitle: "Dancer · Afro-contemporary / Traditional · Akwa Ibom, Nigeria",
      thumbnail: "/assets/img/talents/fatima.jpg",
      portfolioTitle: "Favour Ekanem — Performance Reel",
      portfolioBadge: "4 items",
      portfolioItems: [
        {
          id: 1,
          title: "Roots in Motion",
          subtitle: "Traditional Nigerian · Contemporary",
          duration: "3:28",
        },
        {
          id: 2,
          title: "Rhythm of Home",
          subtitle: "Afro-contemporary",
          duration: "3:42",
          isActive: true,
        },
        {
          id: 3,
          title: "Between Two Worlds",
          subtitle: "Contemporary Fusion",
          duration: "4:01",
        },
        {
          id: 4,
          title: "African Pulse",
          subtitle: "Traditional · Afro-fusion",
          duration: "4:18",
        },
      ],
      upNextVideos: [
        {
          id: "movement-and-identity",
          title: "Movement & Identity",
          artist: "Favour Ekanem",
          duration: "4 : 01",
          thumbnail: "/assets/img/talents/upnext-golden-hour.jpg",
          href: "/talents/favour-ekanem/video/movement-and-identity",
        },
        {
          id: "african-ballet-fusion",
          title: "African Ballet Fusion",
          artist: "Blessing Moses",
          duration: "3 : 28",
          thumbnail: "/assets/img/talents/upnext-beautiful-chaos.jpg",
          href: "/talents/favour-ekanem/video/african-ballet-fusion",
        },
        {
          id: "rhythm-without-borders",
          title: "Rhythm Without Borders",
          artist: "Chisom Okeke",
          duration: "4 : 18",
          thumbnail: "/assets/img/talents/upnext-new-beginnings.jpg",
          href: "/talents/favour-ekanem/video/rhythm-without-borders",
        },
      ],
    },
    relatedCategoryTitle: "More Dancers",
    relatedCreatives: [
      {
        id: "blessing-moses",
        name: "Blessing Moses",
        category: "Afro-contemporary / Ballet",
        image: "/assets/img/talents/studio.jpg",
        slug: "blessing-moses",
      },
      {
        id: "chisom-okeke",
        name: "Chisom Okeke",
        category: "Afro-contemporary",
        image: "/assets/img/talents/amara.jpg",
        slug: "chisom-okeke",
      },
      {
        id: "samuel-ajayi",
        name: "Samuel Ajayi",
        category: "Afrobeats / Popping",
        image: "/assets/img/talents/headphones.jpg",
        slug: "samuel-ajayi",
      },
    ],
  },

  // 5. INFLUENCER — Adaobi Nwankwo
  {
    id: "adaobi-nwankwo",
    slug: "adaobi-nwankwo",
    name: "Adaobi Nwankwo",
    category: "INFLUENCER",
    categoryKey: "influencers",
    badge: "INFLUENCER",
    subtitle: "Influencer · Lifestyle / Fashion · Anambra, Nigeria",
    bio: "Adaobi Nwankwo is a lifestyle and fashion content creator from Anambra, Nigeria, passionate about African creativity, self-expression, and modern culture.",
    rating: "4.9",
    reviewCount: 4.9,
    followers: "119K followers",
    bookingPrice: "₦250,000",
    image: "/assets/img/talents/julius.jpg",
    coverImage: "/assets/img/talents/studio.jpg",
    isHot: true,
    tabs: ["ABOUT", "GALLERY", "VIDEOS"],
    awards: [
      "Rising Lifestyle Creator — Naija Digital Awards 2025",
      "Best Fashion Content Creator Nominee",
      "Royz Houz Digital Creator Spotlight",
    ],
    achievements: [
      "2M+ content views across social platforms",
      "Built a community of 40K+ followers",
      "Collaborated with 20+ emerging brands",
      "Featured in two Nigerian lifestyle publications",
    ],
    socials: {
      facebook: "https://facebook.com",
      youtube: "https://youtube.com",
      instagram: "https://instagram.com",
      twitter: "https://twitter.com",
      tiktok: "https://tiktok.com",
    },
    videoReel: {
      id: "creator-reel",
      title: "Adaobi Nwankwo — Creator Reel",
      subtitle: "Adaobi Nwankwo",
      thumbnail: "/assets/img/talents/studio.jpg",
      portfolioTitle: "Content Portfolio — Adaobi Nwankwo",
      portfolioBadge: "4 items",
      portfolioItems: [
        {
          id: 1,
          title: "African Style Edit",
          subtitle: "Fashion / Lifestyle · 1.4M views",
          duration: "3:28",
        },
        {
          id: 2,
          title: "A Day in Lagos",
          subtitle: "Lifestyle / Travel · 982K views",
          duration: "3:42",
          isActive: true,
        },
        {
          id: 3,
          title: "Creators Behind the Culture",
          subtitle: "Culture / Interview · 756K views",
          duration: "4:01",
        },
        {
          id: 4,
          title: "Style Meets Tradition",
          subtitle: "Fashion / Culture · 624K views",
          duration: "4:18",
        },
      ],
      upNextVideos: [
        {
          id: "behind-the-look",
          title: "Behind the Look",
          artist: "Fashion Series",
          duration: "4 : 01",
          thumbnail: "/assets/img/talents/upnext-golden-hour.jpg",
          href: "/talents/adaobi-nwankwo/video/behind-the-look",
        },
        {
          id: "my-creative-journey",
          title: "My Creative Journey",
          artist: "Lifestyle / Interview",
          duration: "3 : 28",
          thumbnail: "/assets/img/talents/upnext-beautiful-chaos.jpg",
          href: "/talents/adaobi-nwankwo/video/my-creative-journey",
        },
        {
          id: "discovering-nigerian-design",
          title: "Discovering Nigerian Design",
          artist: "Culture / Fashion",
          duration: "4 : 18",
          thumbnail: "/assets/img/talents/upnext-new-beginnings.jpg",
          href: "/talents/adaobi-nwankwo/video/discovering-nigerian-design",
        },
      ],
    },
    relatedCategoryTitle: "More Influencers",
    relatedCreatives: [
      {
        id: "sharon-eze",
        name: "Sharon Eze",
        category: "Lifestyle / Culture",
        image: "/assets/img/talents/zara.jpg",
        slug: "sharon-eze",
      },
      {
        id: "mercy-daniel",
        name: "Mercy Daniel",
        category: "Art / Culture",
        image: "/assets/img/talents/fatima.jpg",
        slug: "mercy-daniel",
      },
      {
        id: "moses-ibrahim",
        name: "Moses Ibrahim",
        category: "Fashion / Lifestyle",
        image: "/assets/img/talents/julius.jpg",
        slug: "moses-ibrahim",
      },
    ],
  },

  // 6. WRITER — Debby Jaden
  {
    id: "debby-jaden",
    slug: "debby-jaden",
    name: "Debby Jaden",
    category: "WRITER",
    categoryKey: "writers",
    badge: "WRITER",
    subtitle: "Fiction / Historical — Kano, Nigeria",
    bio: "Debby Jaden is a Nigerian writer and storyteller whose work explores identity, relationships, culture, and the everyday experiences that shape African lives.",
    rating: "4.9",
    reviewCount: 4.9,
    followers: "125K followers",
    bookingPrice: "₦250,000",
    image: "/assets/img/talents/zara.jpg",
    coverImage: "/assets/img/talents/zara.jpg",
    isHot: true,
    tabs: ["ABOUT", "GALLERY", "VIDEOS", "PUBLICATIONS"],
    awards: [
      "Emerging Screenwriter — Enugu Creative Awards 2025",
      "Best Short Story — Eastern Writers Showcase",
      "Royz Houz Storytelling Fellowship Recipient",
    ],
    achievements: [
      "Facilitated creative-writing workshops for emerging writers",
      "Featured in five literary and creative publications",
      "Published 12+ short stories",
      "Written three completed screenplays",
    ],
    socials: {
      facebook: "https://facebook.com",
      youtube: "https://youtube.com",
      instagram: "https://instagram.com",
      twitter: "https://twitter.com",
      tiktok: "https://tiktok.com",
    },
    publications: [
      { title: "Echoes of the River", type: "Novel", year: "2024" },
      { title: "Beneath the Baobab", type: "Short Story Collection", year: "2023" },
      { title: "Lagos in Solitude", type: "Screenplay", year: "2025" },
    ],
    videoReel: {
      id: "letters-from-home",
      title: "Letters From Home",
      subtitle: "Debby Jaden",
      thumbnail: "/assets/img/talents/zara.jpg",
      portfolioTitle: "Writing Portfolio — Debby Jaden",
      portfolioBadge: "4 portfolios",
      portfolioItems: [
        {
          id: 1,
          title: "Letters From Home",
          subtitle: "Creative Nonfiction",
          duration: "8 min read",
        },
        {
          id: 2,
          title: "The Things We Don't Say",
          subtitle: "Short Fiction",
          duration: "12 min read",
          isActive: true,
        },
        {
          id: 3,
          title: "Where We Come From",
          subtitle: "Essay / Culture",
          duration: "10 min read",
        },
        {
          id: 4,
          title: "After the Rain",
          subtitle: "Poetry",
          duration: "5 min read",
        },
      ],
      upNextVideos: [
        {
          id: "the-weight-of-expectations",
          title: "The Weight of Expectations",
          artist: "Personal Essay",
          duration: "4 : 01",
          thumbnail: "/assets/img/talents/upnext-golden-hour.jpg",
          href: "/talents/debby-jaden/video/the-weight-of-expectations",
        },
        {
          id: "a-home-between-two-worlds",
          title: "A Home Between Two Worlds",
          artist: "Short Fiction",
          duration: "3 : 28",
          thumbnail: "/assets/img/talents/upnext-beautiful-chaos.jpg",
          href: "/talents/debby-jaden/video/a-home-between-two-worlds",
        },
        {
          id: "what-we-leave-behind",
          title: "What We Leave Behind",
          artist: "Creative Nonfiction",
          duration: "4 : 18",
          thumbnail: "/assets/img/talents/upnext-new-beginnings.jpg",
          href: "/talents/debby-jaden/video/what-we-leave-behind",
        },
      ],
    },
    relatedCategoryTitle: "More Writers",
    relatedCreatives: [
      {
        id: "daniel-okoro",
        name: "Daniel Okoro",
        category: "Fiction / Drama",
        image: "/assets/img/talents/kofi.jpg",
        slug: "daniel-okoro",
      },
      {
        id: "amara-nwosu",
        name: "Amara Nwosu",
        category: "Poetry / Creative Nonfiction",
        image: "/assets/img/talents/amara.jpg",
        slug: "amara-nwosu",
      },
      {
        id: "amaka-chukwu",
        name: "Amaka Chukwu",
        category: "Screenwriter / Film",
        image: "/assets/img/talents/studio.jpg",
        slug: "amaka-chukwu",
      },
    ],
  },

  // 7. Goodness Lawrence (Writer)
  {
    id: "goodness-lawrence",
    slug: "goodness-lawrence",
    name: "Goodness Lawrence",
    category: "WRITER",
    categoryKey: "writers",
    badge: "WRITER",
    subtitle: "Poetry / Creative Writing — Bauchi, Nigeria",
    bio: "Poet exploring identity, relationships, and social change through vivid imagery and thought-provoking spoken word performances across Africa.",
    rating: "5",
    reviewCount: 5.0,
    followers: "85K",
    bookingPrice: "₦200,000",
    image: "/assets/img/talents/zara.jpg",
    coverImage: "/assets/img/talents/zara.jpg",
    isHot: true,
    tabs: ["ABOUT", "GALLERY", "VIDEOS", "PUBLICATIONS"],
    awards: [
      "National Poetry Slam Winner 2024",
      "Bauchi Literary Excellence Award",
    ],
    achievements: [
      "Published 2 spoken word anthologies",
      "Featured at Lagos International Poetry Festival",
      "Facilitated youth poetry workshops across Northern Nigeria",
    ],
    socials: {
      facebook: "https://facebook.com",
      youtube: "https://youtube.com",
      instagram: "https://instagram.com",
      twitter: "https://twitter.com",
      tiktok: "https://tiktok.com",
    },
    relatedCategoryTitle: "More Writers",
    relatedCreatives: [
      {
        id: "debby-jaden",
        name: "Debby Jaden",
        category: "Writer · Fiction",
        image: "/assets/img/talents/zara.jpg",
        slug: "debby-jaden",
      },
      {
        id: "daniel-okoro",
        name: "Daniel Okoro",
        category: "Fiction / Drama",
        image: "/assets/img/talents/kofi.jpg",
        slug: "daniel-okoro",
      },
      {
        id: "amara-nwosu",
        name: "Amara Nwosu",
        category: "Poetry / Creative Nonfiction",
        image: "/assets/img/talents/amara.jpg",
        slug: "amara-nwosu",
      },
    ],
  },

  // 8. Kenneth Davis (Musician)
  {
    id: "kenneth-davis-directory",
    slug: "kenneth-davis",
    name: "Kenneth Davis",
    category: "MUSICIAN",
    categoryKey: "musicians",
    badge: "MUSIC",
    subtitle: "Afro-Fusion / Guitarist — Lagos, Nigeria",
    bio: "Master instrumentalist and composer pioneering new waves of modern African jazz fusion, having collaborated with top international artists.",
    rating: "4.5",
    reviewCount: 4.5,
    followers: "140K",
    bookingPrice: "₦350,000",
    image: "/assets/img/talents/amara.jpg",
    coverImage: "/assets/img/talents/amara.jpg",
    isHot: true,
    tabs: ["ABOUT", "GALLERY", "VIDEOS", "MUSIC"],
    awards: [
      "Afro-Jazz Guitarist of the Year 2024",
      "Lagos Live Music Excellence Award",
    ],
    achievements: [
      "Over 100 live stadium & festival performances",
      "Headlined West Africa Jazz Festival",
      "Composer on 3 major motion picture scores",
    ],
    socials: {
      facebook: "https://facebook.com",
      youtube: "https://youtube.com",
      instagram: "https://instagram.com",
      twitter: "https://twitter.com",
      tiktok: "https://tiktok.com",
    },
    musicTracks: [
      { title: "Strings of Eko", duration: "4:02", streams: "1.5M" },
      { title: "Abuja Sunsets", duration: "3:30", streams: "720K" },
    ],
    relatedCategoryTitle: "More Musicians",
    relatedCreatives: [
      {
        id: "zara-diallo",
        name: "Zara Diallo",
        category: "Musician · Vocalist",
        image: "/assets/img/talents/zara.jpg",
        slug: "zara-diallo",
      },
      {
        id: "blessing-moses",
        name: "Blessing Moses",
        category: "Musician",
        image: "/assets/img/talents/blessing.jpg",
        slug: "blessing-moses",
      },
      {
        id: "tee-brown",
        name: "Tee Brown",
        category: "Musician",
        image: "/assets/img/talents/emeka.jpg",
        slug: "tee-brown",
      },
    ],
  },

  // 9. Mercy Udo (Producer)
  {
    id: "mercy-udo",
    slug: "mercy-udo",
    name: "Mercy Udo",
    category: "PRODUCER",
    categoryKey: "producers",
    badge: "PRODUCER",
    subtitle: "Highlife / Afrobeats — Rivers, Nigeria",
    bio: "Innovative producer crafting layered beats with authentic African live percussion, brass, and rich polyrhythms.",
    rating: "5",
    reviewCount: 5.0,
    followers: "98K",
    bookingPrice: "₦450,000",
    image: "/assets/img/talents/blessing.jpg",
    coverImage: "/assets/img/talents/producer-hero.jpg",
    isHot: true,
    tabs: ["ABOUT", "GALLERY", "VIDEOS"],
    awards: ["Port Harcourt Music Producer of the Year 2023"],
    achievements: [
      "Produced top 10 charting singles",
      "Over 10M cumulative digital streams",
    ],
    socials: {
      facebook: "https://facebook.com",
      youtube: "https://youtube.com",
      instagram: "https://instagram.com",
      twitter: "https://twitter.com",
      tiktok: "https://tiktok.com",
    },
    relatedCategoryTitle: "More Producers",
    relatedCreatives: [
      {
        id: "julius-ayomide",
        name: "Julius Ayomide",
        category: "Producer",
        image: "/assets/img/talents/julius.jpg",
        slug: "julius-ayomide",
      },
      {
        id: "peace-ojo",
        name: "Peace Ojo",
        category: "Producer",
        image: "/assets/img/talents/studio.jpg",
        slug: "peace-ojo",
      },
      {
        id: "janet-obi",
        name: "Janet Obi",
        category: "Producer",
        image: "/assets/img/talents/headphones.jpg",
        slug: "janet-obi",
      },
    ],
  },

  // 10. Micheal Bradley (Actor)
  {
    id: "micheal-bradley",
    slug: "micheal-bradley",
    name: "Micheal Bradley",
    category: "ACTOR",
    categoryKey: "actors",
    badge: "ACTOR",
    subtitle: "Drama / Film — Imo, Nigeria",
    bio: "Dynamic screen and stage performer known for intense dramatic depth, emotional range, and captivating cinematic presence.",
    rating: "4.8",
    reviewCount: 4.8,
    followers: "150K",
    bookingPrice: "₦300,000",
    image: "/assets/img/talents/micheal.jpg",
    coverImage: "/assets/img/talents/micheal.jpg",
    isHot: true,
    tabs: ["ABOUT", "GALLERY", "VIDEOS"],
    awards: ["Nollywood Rising Star Nominee 2024"],
    achievements: [
      "Lead in 5 feature films distributed internationally",
      "Best Actor Award at Eastern Screen Festival",
    ],
    socials: {
      facebook: "https://facebook.com",
      youtube: "https://youtube.com",
      instagram: "https://instagram.com",
      twitter: "https://twitter.com",
      tiktok: "https://tiktok.com",
    },
    relatedCategoryTitle: "More Actors",
    relatedCreatives: [
      {
        id: "jenny-donald",
        name: "Jenny Donald",
        category: "Actor · Drama",
        image: "/assets/img/talents/kofi.jpg",
        slug: "jenny-donald",
      },
      {
        id: "daniel-nwosu",
        name: "Daniel Nwosu",
        category: "Actor · Drama / Film",
        image: "/assets/img/talents/studio.jpg",
        slug: "daniel-nwosu",
      },
      {
        id: "amaka-eze",
        name: "Amaka Eze",
        category: "Actress · Drama / Romance",
        image: "/assets/img/talents/amara.jpg",
        slug: "amaka-eze",
      },
    ],
  },
];

// Re-export helper functions from dedicated utils module for compatibility
export { getTalentBySlug, getRelatedTalents } from "@/utils/talentHelpers";

