/**
 * Featured Talents Data (for Home Page — 8 Featured Talents)
 */
export const FEATURED_TALENTS = [
  {
    id: "julius-ayomide",
    name: "Julius Ayomide",
    category: "INFLUENCER",
    genre: "Afrobeats / R&B",
    location: "Lagos, Nigeria",
    rating: "4.9",
    followers: "125K",
    image: "/assets/img/talents/julius.jpg",
    isHot: true,
  },
  {
    id: "zara-diallo",
    name: "Zara Diallo",
    category: "WRITER",
    genre: "Afrobeats / R&B",
    location: "Lagos, Nigeria",
    rating: "4.9",
    followers: "125K",
    image: "/assets/img/talents/zara.jpg",
    isHot: true,
  },
  {
    id: "fatima-ibrahim",
    name: "Fatima ibrahim",
    category: "DANCER",
    genre: "Afrobeats / R&B",
    location: "Lagos, Nigeria",
    rating: "4.9",
    followers: "125K",
    image: "/assets/img/talents/fatima.jpg",
    isHot: true,
  },
  {
    id: "kenneth-davis",
    name: "Kenneth Davis",
    category: "MUSICIAN",
    genre: "Afrobeats / R&B",
    location: "Abuja, Nigeria",
    rating: "4.9",
    followers: "125K",
    image: "/assets/img/talents/amara.jpg",
    isHot: true,
  },
  {
    id: "emeka-nwosu",
    name: "Emeka Nwosu",
    category: "PRODUCER",
    genre: "Afrobeats / R&B",
    location: "Lagos, Nigeria",
    rating: "4.9",
    followers: "125K",
    image: "/assets/img/talents/emeka.jpg",
    isHot: true,
  },
  {
    id: "blessing-moses",
    name: "Blessing Moses",
    category: "DESIGNER",
    genre: "Afrobeats / R&B",
    location: "Lagos, Nigeria",
    rating: "4.9",
    followers: "125K",
    image: "/assets/img/talents/blessing.jpg",
    isHot: true,
  },
  {
    id: "jenny-donald",
    name: "Jenny Donald",
    category: "ACTOR",
    genre: "Afrobeats / R&B",
    location: "Abuja, Nigeria",
    rating: "4.9",
    followers: "125K",
    image: "/assets/img/talents/kofi.jpg",
    isHot: true,
  },
  {
    id: "charles-moses",
    name: "Charles Moses",
    category: "MUSICIAN",
    genre: "Afrobeats / R&B",
    location: "Abuja, Nigeria",
    rating: "4.9",
    followers: "125K",
    image: "/assets/img/talents/charles.jpg",
    isHot: true,
  },
];

/**
 * Trending Talents Data (for Talents Page /talent-hub)
 */
export const TRENDING_TALENTS = [
  {
    id: "amara-nwosu",
    name: "Amara Nwosu",
    profession: "Musician",
    image: "/assets/img/talents/amara.jpg",
    alt: "Amara Nwosu - Musician",
  },
  {
    id: "zara-diallo",
    name: "Zara Diallo",
    profession: "Dancer",
    image: "/assets/img/talents/zara.jpg",
    alt: "Zara Diallo - Dancer",
  },
  {
    id: "julius-ayomide",
    name: "Julius Ayomide",
    profession: "Actor",
    image: "/assets/img/talents/julius.jpg",
    alt: "Julius Ayomide - Actor",
  },
  {
    id: "fatima-ibrahim",
    name: "Fatima Ibrahim",
    profession: "Writer",
    image: "/assets/img/talents/fatima.jpg",
    alt: "Fatima Ibrahim - Writer",
  },
];
